import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import type { ExecutionEvent, Snapshot, Workspace, SessionInfo, SessionOptions, PromptAttachment, ActiveSessionSummary } from '../shared/types.ts';
import ExecutionPanel from './ExecutionPanel.tsx';
import ChatItem from './ChatMessage.tsx';
import DirectoryPicker from './DirectoryPicker.tsx';
import SettingsPage from './SettingsPage.tsx';
import KitRunCard, { type KitJob } from './KitRunCard.tsx';
import PetWidget from './PetWidget.tsx';
import { loadPreferences, savePreferences } from './preferences.ts';
import type { ConsolePreferences } from './preferences.ts';
import { connectionLabel, filterSessions, groupWorkspaces, recentIssue, validQuickPrompts } from './ui-logic.ts';
import './style.css';
const jsonResponse = async (r:Response) => {
  if(!r.headers.get('content-type')?.includes('application/json')) throw Error('Connection lost or Access sign-in required. Reload this page to sign in.');
  const data=await r.json();if(!r.ok) throw Error(r.status===401?'Cloudflare Access sign-in required. Reload this page.':data.error??`HTTP ${r.status}`);return data;
};
const get = async (url: string) => jsonResponse(await fetch(url,{cache:'no-store'}));
const post = async (url: string, value: object) => jsonResponse(await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(value) }));
function App() {
  const [workspaces, setWorkspaces] = useState<Workspace[]>([]); const [workspace,setWorkspace]=useState(''); const [path,setPath]=useState('');
  const [workspaceQuery,setWorkspaceQuery]=useState(''); const [workspaceName,setWorkspaceName]=useState('');const [workspaceTools,setWorkspaceTools]=useState(false);
  const [browseOpen,setBrowseOpen]=useState(false);const browseTrigger=useRef<HTMLButtonElement>(null);
  const [sessions,setSessions]=useState<SessionInfo[]>([]);const [session,setSession]=useState('');const [sessionQuery,setSessionQuery]=useState('');
  const [activity,setActivity]=useState<ActiveSessionSummary[]>([]);
  const [dismissed,setDismissed]=useState<string[]>(()=>{try{const value=JSON.parse(localStorage.getItem('pi-console-dismissed-completions')??'[]');return Array.isArray(value)?value.filter((s:unknown)=>typeof s==='string').slice(-200):[]}catch{return []}});
  const [dismissedIssues,setDismissedIssues]=useState<string[]>(()=>{try{const value=JSON.parse(localStorage.getItem('pi-console-dismissed-issues')??'[]');return Array.isArray(value)?value.filter((s:unknown)=>typeof s==='string').slice(-200):[]}catch{return []}});
  const dismissIssue=(id:string)=>setDismissedIssues(old=>{const next=[...old.filter(x=>x!==id),id].slice(-200);localStorage.setItem('pi-console-dismissed-issues',JSON.stringify(next));return next});
  const dismissCompletion=(id:string)=>{setDismissed(old=>{const next=[...old.filter(x=>x!==id),id].slice(-200);localStorage.setItem('pi-console-dismissed-completions',JSON.stringify(next));return next})};
  const [promptHistoryOpen,setPromptHistoryOpen]=useState(false);const [promptHistoryLimit,setPromptHistoryLimit]=useState(80);
  const [snapshot,setSnapshot]=useState<Snapshot>(); const [executionEvents,setExecutionEvents]=useState<ExecutionEvent[]>([]);
  const [prompt,setPrompt]=useState(''); const [lastSubmitted,setLastSubmitted]=useState('');
  const [executionTarget,setExecutionTarget]=useState<'pi'|'kit'>('pi');
  const [kitStatus,setKitStatus]=useState<{available:boolean;job?:KitJob}>({available:false});
  const [options,setOptions]=useState<SessionOptions>();const [optionsBusy,setOptionsBusy]=useState(false);
  const [attachments,setAttachments]=useState<File[]>([]);const [attachmentError,setAttachmentError]=useState('');const [sending,setSending]=useState(false);const attachRef=useRef<HTMLInputElement>(null);
  const [error,setError]=useState('');const [sse,setSse]=useState<'offline'|'connecting'|'connected'|'reconnecting'>('offline');
  const [server,setServer]=useState(true);const [online,setOnline]=useState(navigator.onLine);
  type View='workspaces'|'sessions'|'chat'|'execution'|'settings';
  const initial=useRef<{view:View;workspace:string;session:string}|null>(null);
  if(!initial.current){const state=history.state;const valid=['workspaces','sessions','chat','execution','settings'];initial.current=state?.piConsoleNav&&valid.includes(state.view)?{view:state.view,workspace:typeof state.workspace==='string'?state.workspace:'',session:typeof state.session==='string'?state.session:''}:{view:new URLSearchParams(location.search).get('view')==='settings'?'settings':'workspaces',workspace:'',session:''}}
  const start=initial.current;
  const [mobileView,setMobileView]=useState<View>(start.view);
  const [preferences,setPreferences]=useState<ConsolePreferences>(loadPreferences);
  const [quickPrompts,setQuickPrompts]=useState<string[]>([]);const [editPrompts,setEditPrompts]=useState(false);const [quickDraft,setQuickDraft]=useState('');
  const [newContent,setNewContent]=useState(false);const [connectionEpoch,setConnectionEpoch]=useState(0);
  const ref=useRef<Snapshot|undefined>(undefined);const activityVersion=useRef(0);const refreshTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const chatRef=useRef<HTMLDivElement>(null);
  const followRef=useRef(true);const searchRef=useRef<HTMLInputElement>(null);const composerRef=useRef<HTMLTextAreaElement>(null);
  const navigate=(view:View,nextWorkspace=workspace,nextSession=session)=>{const next={piConsoleNav:true,view,workspace:nextWorkspace,session:nextSession,...(view==='settings'?{fromConsole:true}:{})};if(view===mobileView&&nextWorkspace===workspace&&nextSession===session)return;history.pushState(next,'',view==='settings'?'?view=settings':location.pathname);setMobileView(view);if(nextWorkspace!==workspace)setWorkspace(nextWorkspace);if(nextSession!==session)setSession(nextSession)};
  const updatePreferences=(value:ConsolePreferences)=>{setPreferences(value);savePreferences(value)};
  useEffect(()=>{document.documentElement.dataset.appearance=preferences.appearance},[preferences.appearance]);
  useEffect(()=>{const initialState=start;setWorkspace(initialState.workspace);setSession(initialState.session);history.replaceState({piConsoleNav:true,...initialState,...(history.state?.fromConsole?{fromConsole:true}:{})},'',location.href);const pop=(event:PopStateEvent)=>{const nav=event.state;if(!nav?.piConsoleNav)return;setWorkspace(nav.workspace??'');setSession(nav.session??'');setMobileView(nav.view??'workspaces')};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[]);
  const current=workspaces.find(w=>w.id===workspace);const selected=sessions.find(s=>s.id===session);
  const groups=useMemo(()=>groupWorkspaces(workspaces,workspaceQuery),[workspaces,workspaceQuery]);
  const availableWorkspaces=[...groups.pinned,...groups.recent,...groups.all].filter(w=>w.valid!==false);
  const unavailableWorkspaces=[...groups.pinned,...groups.recent,...groups.all].filter(w=>w.valid===false);
  const visibleSessions=useMemo(()=>filterSessions(sessions,sessionQuery),[sessions,sessionQuery]);
  const promptHistory=useMemo(()=>snapshot?.chat.filter(m=>m.role==='user')??[],[snapshot?.chat]);
  const visibleActivity=activity.filter(s=>s.running||s.decisionCount||s.completion&&!dismissed.includes(s.completion.id));
  const needsInput=visibleActivity.filter(s=>s.decisionCount>0).length;const activeCount=visibleActivity.filter(s=>s.running).length;
  const completedCount=visibleActivity.filter(s=>s.completion&&!dismissed.includes(s.completion.id)).length;
  const activeTool=snapshot?.execution.nodes.slice().reverse().find(n=>n.kind==='tool'&&n.status==='running');
  const activityLabel=activeTool?`${activeTool.label}${activeTool.action?` · ${activeTool.action}`:''}`:snapshot?.activeRunId?'Pi is processing…':undefined;
  const status=!session&&server&&online?'Server ready · no Pi session':connectionLabel({online,server,sse,runtime:snapshot?.runtime});
  const running=snapshot?.execution.nodes.filter(n=>n.status==='running').length??0;
  const blocked=snapshot?.execution.nodes.filter(n=>n.status==='blocked').length??0;
  const failures=recentIssue(snapshot?.events??[],dismissedIssues);
  const refreshWorkspaces=async()=>{try{const d=await get('/api/workspaces');setWorkspaces(d.workspaces);setServer(true);setError('');}catch(e){setServer(false);setError((e as Error).message);}};
  const refreshActivity=async()=>{const version=++activityVersion.current;try{const d=await get('/api/activity');if(version===activityVersion.current)setActivity(Array.isArray(d.sessions)?d.sessions:[])}catch{if(version===activityVersion.current)setActivity([])}};
  const refreshSessions=async(id=workspace)=>{if(!id)return;try{const d=await get(`/api/sessions?workspaceId=${encodeURIComponent(id)}`);setSessions(d.sessions);}catch(e){setError((e as Error).message);}};
  useEffect(()=>{void refreshWorkspaces();get('/api/quick-prompts').then(d=>setQuickPrompts(d.prompts)).catch(()=>{});
    const offline=()=>setOnline(false),ready=()=>setOnline(true);window.addEventListener('offline',offline);window.addEventListener('online',ready);
    return()=>{window.removeEventListener('offline',offline);window.removeEventListener('online',ready)};
  },[]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();navigate(workspace?'sessions':'workspaces');if(workspace)requestAnimationFrame(()=>searchRef.current?.focus());}};
    window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);
  },[workspace]);
  useEffect(()=>{if(!workspace)return;void refreshSessions(workspace);const interval=setInterval(()=>void refreshSessions(workspace),10000);return()=>clearInterval(interval)},[workspace]);
  useEffect(()=>{void refreshActivity();const interval=setInterval(()=>void refreshActivity(),5000);return()=>clearInterval(interval)},[]);
  useEffect(()=>{if(!workspace||!session){setOptions(undefined);return;}let cancelled=false;setOptions(undefined);
    get(`/api/session/options?workspaceId=${encodeURIComponent(workspace)}&sessionId=${encodeURIComponent(session)}`).then(d=>{if(!cancelled)setOptions(d)}).catch(e=>{if(!cancelled)setError((e as Error).message)});
    return()=>{cancelled=true};
  },[workspace,session]);
  useEffect(()=>{
    if(!workspace||!session)return;
    let cancelled=false;let stream:EventSource|undefined;let timer:ReturnType<typeof setTimeout>|undefined;
    setSse('connecting');
    const refresh=async()=>{const data:Snapshot=await get(`/api/state?workspaceId=${encodeURIComponent(workspace)}&sessionId=${encodeURIComponent(session)}`);if(cancelled||ref.current&&data.seq<ref.current.seq)return;ref.current=data;setSnapshot(data);setExecutionEvents(data.events);setServer(true);};
    const reconnect=async()=>{if(cancelled)return;
      try{await get('/api/workspaces');setServer(true);}catch(e){setServer(false);setError((e as Error).message);timer=setTimeout(()=>void reconnect(),2500);return;}
      try{try{await refresh();}catch{const resumed=await post('/api/resume',{workspaceId:workspace,sessionId:session});if(cancelled)return;ref.current=resumed.snapshot;setSnapshot(resumed.snapshot);setExecutionEvents(resumed.snapshot.events);}
        setError('');if(ref.current)connect(ref.current.seq);
      }catch(e){if(cancelled)return;setError((e as Error).message);setSse('offline');timer=setTimeout(()=>void reconnect(),2500)}
    };
    const connect=(cursor:number)=>{
      if(cancelled)return;stream?.close();stream=new EventSource(`/api/events?workspaceId=${encodeURIComponent(workspace)}&sessionId=${encodeURIComponent(session)}&since=${cursor}`);
      stream.onopen=()=>{setSse('connected');setServer(true)};
      stream.onerror=()=>{stream?.close();if(cancelled)return;setSse('reconnecting');timer=setTimeout(()=>void reconnect(),1200)};
      stream.addEventListener('execution',e=>{
        const event:ExecutionEvent=JSON.parse((e as MessageEvent).data),before=ref.current;
        if(!before||event.seq<=before.seq)return;if(event.seq!==before.seq+1){void refresh().catch(()=>{setSse('reconnecting');stream?.close();timer=setTimeout(()=>void reconnect(),1200)});return;}
        let chat=before.chat;
        if(event.type==='MessageStarted')chat=[...chat,{id:event.entityId,role:'assistant',text:'',complete:false}];
        if(event.type==='MessageDelta')chat=chat.map(m=>m.id===event.entityId?{...m,text:m.text+String(event.payload.delta??'')}:m);
        if(event.type==='MessageCompleted')chat=chat.map(m=>m.id===event.entityId?{...m,text:String(event.payload.text??''),complete:true}:m);
        if(event.type==='RunCompleted'||event.type==='RunFailed')void get(`/api/session/options?workspaceId=${encodeURIComponent(workspace)}&sessionId=${encodeURIComponent(session)}`).then(setOptions).catch(()=>{});
        if(['RunStarted','RunCompleted','RunFailed','DecisionRequired','DecisionResolved','AgentStarted','AgentCompleted','AgentFailed'].includes(event.type)||(event.type==='ExecutionNodeUpdated'&&event.source==='pi-subagents'))void refreshActivity();
        const next:Snapshot={...before,runtime:event.type==='RunFailed'&&event.status==='interrupted'?'failed':before.runtime,
          seq:event.seq,events:[...before.events,event].slice(-5000),chat,
          activeRunId:event.type==='RunStarted'?event.runId:event.type==='RunCompleted'||event.type==='RunFailed'?undefined:before.activeRunId};
        ref.current=next;setSnapshot(next);if(event.type!=='MessageDelta')setExecutionEvents(next.events);
        if(['RunStarted','RunCompleted','RunFailed','ToolStarted','ToolProgress','ToolCompleted','ToolFailed','ExecutionNodeUpdated','AgentStarted','AgentProgress','AgentCompleted','AgentFailed','DecisionRequired','DecisionResolved'].includes(event.type)){
          if(refreshTimer.current)clearTimeout(refreshTimer.current);refreshTimer.current=setTimeout(()=>void refresh().catch(()=>{setSse('reconnecting');stream?.close();timer=setTimeout(()=>void reconnect(),1200)}),120);
        }
      });
    };
    post('/api/resume',{workspaceId:workspace,sessionId:session}).then(({snapshot:first}:{snapshot:Snapshot})=>{
      if(cancelled)return;ref.current=first;setSnapshot(first);setExecutionEvents(first.events);setServer(true);setError('');connect(first.seq);
    }).catch(e=>{if(!cancelled){setError((e as Error).message);setSse('offline')}});
    return()=>{cancelled=true;stream?.close();if(timer)clearTimeout(timer);if(refreshTimer.current)clearTimeout(refreshTimer.current);setSse('offline')};
  },[workspace,session,connectionEpoch]);
  useEffect(()=>{setExecutionTarget('pi');setKitStatus({available:false});if(!workspace||!session)return;let cancelled=false;
    const refresh=()=>get(`/api/orchestrator?workspaceId=${encodeURIComponent(workspace)}&sessionId=${encodeURIComponent(session)}`).then(d=>{if(!cancelled)setKitStatus(d)}).catch(()=>{if(!cancelled)setKitStatus({available:false})});
    void refresh();const timer=setInterval(()=>void refresh(),2000);return()=>{cancelled=true;clearInterval(timer)};
  },[workspace,session]);
  useEffect(()=>{const box=chatRef.current;if(!box)return;if(followRef.current){requestAnimationFrame(()=>box.scrollTo({top:box.scrollHeight,behavior:'instant'}));setNewContent(false);}else setNewContent(true)},[snapshot?.chat.at(-1)?.text,snapshot?.chat.length]);
  async function switchWorkspace(id:string,created?:Workspace){const item=created??workspaces.find(w=>w.id===id);if(!item)return;try{await post('/api/workspaces/update',{id,open:true});setWorkspace(id);setWorkspaceName(item.name);setSession('');setSessions([]);ref.current=undefined;setSnapshot(undefined);setExecutionEvents([]);setOptions(undefined);setAttachments([]);navigate('sessions',id,'');setWorkspaceTools(false);await refreshWorkspaces();setError('');}catch(e){setError((e as Error).message)}}
  async function updateWorkspace(changes:object){if(!workspace)return;try{const d=await post('/api/workspaces/update',{id:workspace,...changes});setWorkspaceName(d.workspace.name);await refreshWorkspaces();setError('')}catch(e){setError((e as Error).message)}}
  async function removeWorkspace(item:Workspace){if(!window.confirm(`Remove “${item.name}” from Pi Console? The folder and Pi sessions will stay on disk.`))return;try{await post('/api/workspaces/remove',{id:item.id});if(workspace===item.id){setWorkspace('');setSession('');setSessions([]);ref.current=undefined;setSnapshot(undefined);setExecutionEvents([]);setOptions(undefined);setWorkspaceTools(false);navigate('workspaces','','')}await refreshWorkspaces();void refreshActivity();setError('')}catch(e){setError((e as Error).message)}}
  async function addWorkspace(){try{const d=await post('/api/workspaces',{path});await refreshWorkspaces();await switchWorkspace(d.workspace.id,d.workspace);setPath('')}catch(e){setError((e as Error).message)}}
  async function newSession(){try{const d=await post('/api/sessions',{workspaceId:workspace});setSessions(current=>[d.session,...current]);ref.current=undefined;setSnapshot(undefined);setExecutionEvents([]);setOptions(undefined);setAttachments([]);navigate(preferences.defaultSessionView,workspace,d.session.id);setError('')}catch(e){setError((e as Error).message)}}
  async function changeModel(provider:string,modelId:string){if(!session||optionsBusy)return;setOptionsBusy(true);try{setOptions(await post('/api/session/model',{workspaceId:workspace,sessionId:session,provider,modelId}));setError('')}catch(e){setError((e as Error).message)}finally{setOptionsBusy(false)}}
  async function changeThinking(level:string){if(!session||optionsBusy)return;setOptionsBusy(true);try{setOptions(await post('/api/session/thinking',{workspaceId:workspace,sessionId:session,level}));setError('')}catch(e){setError((e as Error).message)}finally{setOptionsBusy(false)}}
  const attachmentType=(file:File)=>{
    if(['image/png','image/jpeg','image/gif','image/webp'].includes(file.type))return {kind:'image',mimeType:file.type} as const;
    const imageExt=file.name.toLowerCase().match(/\.(png|jpe?g|gif|webp)$/)?.[1];
    if(imageExt)return {kind:'image',mimeType:`image/${imageExt==='jpg'?'jpeg':imageExt}` as string} as const;
    if(file.type.startsWith('text/')||['application/json','application/xml','application/javascript'].includes(file.type))return {kind:'text',mimeType:file.type} as const;
    if(/\.(txt|md|json|ts|tsx|js|jsx|css|html?|xml|ya?ml|py|go|rs|ps1|sh|log|csv|svg|c|h|cpp|hpp|java|rb|swift|kt|toml|ini|sql|vue|svelte)$/i.test(file.name))return {kind:'text',mimeType:'text/plain'} as const;
    return undefined;
  };
  function addAttachments(files:FileList|null){if(!files)return;const next=[...attachments,...Array.from(files)];attachRef.current!.value='';
    if(next.length>4){setAttachmentError('Up to 4 files can be attached.');return}
    if(next.some(file=>!file.name||file.name.length>120||file.name.includes('/')||file.name.includes('\\')||!attachmentType(file)||!file.size||file.size>(attachmentType(file)?.kind==='image'?5*1024*1024:64*1024)) || next.reduce((total,file)=>total+file.size,0)>8*1024*1024){setAttachmentError('Choose text files up to 64 KiB or PNG/JPEG/GIF/WebP images up to 5 MiB (8 MiB total).');return}
    setAttachmentError('');setAttachments(next);
  }
  async function serializeAttachments():Promise<PromptAttachment[]>{return Promise.all(attachments.map(async file=>{
    const type=attachmentType(file)!;
    if(type.kind==='text')return {kind:'text',name:file.name,mimeType:type.mimeType,text:await file.text()};
    const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]??'');reader.onerror=()=>reject(Error('Could not read attached image'));reader.readAsDataURL(file)});
    return {kind:'image',name:file.name,mimeType:type.mimeType,data};
  }));}
  async function send(){if(!session||(!prompt.trim()&&executionTarget==='kit'||!prompt.trim()&&!attachments.length)||snapshot?.activeRunId||kitStatus.job?.running||sending)return;const message=prompt;setSending(true);
    try{if(executionTarget==='kit'){if(attachments.length)throw Error('Attachments are not supported by ludi-agent-kit runs.');const d=await post('/api/orchestrator/start',{workspaceId:workspace,sessionId:session,request:message});setKitStatus({available:true,job:d.job});setPrompt('');navigate('execution');}
      else{const files=await serializeAttachments();await post('/api/prompt',{workspaceId:workspace,sessionId:session,message,attachments:files});setLastSubmitted(message);setPrompt('');setAttachments([]);setAttachmentError('');const data=await get(`/api/state?workspaceId=${encodeURIComponent(workspace)}&sessionId=${encodeURIComponent(session)}`);if(!ref.current||data.seq>=ref.current.seq){ref.current=data;setSnapshot(data);setExecutionEvents(data.events);}void refreshSessions();followRef.current=true;void refreshActivity();}setError('');}catch(e){setError((e as Error).message)}finally{setSending(false)}}
  async function stop(){try{await post('/api/stop',{workspaceId:workspace,sessionId:session});setError('')}catch(e){setError((e as Error).message)}}
  async function recycleSession(item:SessionInfo){if(!workspace||!window.confirm(`Move “${item.name??'New conversation'}” to this server’s Windows Recycle Bin? This Pi session may also be used by other apps.`))return;try{await post('/api/session/recycle',{workspaceId:workspace,sessionId:item.id});setSessions(current=>current.filter(s=>s.id!==item.id));if(session===item.id){ref.current=undefined;setSnapshot(undefined);setExecutionEvents([]);setOptions(undefined);navigate('sessions',workspace,'')}void refreshActivity();setError('')}catch(e){setError((e as Error).message)}}
  function reopen(){setError('');setConnectionEpoch(v=>v+1)}
  async function savePrompts(){const values=quickDraft.split('\n').map(s=>s.trim()).filter(Boolean);if(!validQuickPrompts(values)){setError('Up to 8 prompts, 200 characters each');return}try{const d=await post('/api/quick-prompts',{prompts:values});setQuickPrompts(d.prompts);setEditPrompts(false);setError('')}catch(e){setError((e as Error).message)}}
  const chooseSession=(id:string)=>{ref.current=undefined;setSnapshot(undefined);setExecutionEvents([]);setOptions(undefined);setAttachments([]);setPromptHistoryOpen(false);navigate(preferences.defaultSessionView,workspace,id);followRef.current=true};
  const openActive=(item:ActiveSessionSummary)=>{if(item.workspaceId!==workspace){setSessions([]);void refreshSessions(item.workspaceId)}ref.current=undefined;setSnapshot(undefined);setExecutionEvents([]);setOptions(undefined);setAttachments([]);setPromptHistoryOpen(false);navigate('chat',item.workspaceId,item.sessionId);followRef.current=true};
  const jumpToPrompt=(id:string)=>{setPromptHistoryOpen(false);const box=chatRef.current;const node=Array.from(box?.querySelectorAll<HTMLElement>('[data-message-id]')??[]).find(el=>el.dataset.messageId===id);if(!box||!node)return;followRef.current=false;box.scrollTo({top:node.getBoundingClientRect().top-box.getBoundingClientRect().top+box.scrollTop-12,behavior:'smooth'});requestAnimationFrame(()=>node.focus({preventScroll:true}))};
  const usePrompt=(value:string)=>{setPrompt(prev=>prev?`${prev.trimEnd()}\n${value}`:value);composerRef.current?.focus()};
  const onComposerKey=(e:React.KeyboardEvent<HTMLTextAreaElement>)=>{if(e.nativeEvent.isComposing)return;if(e.key==='Enter'&&((e.ctrlKey||e.metaKey)||(!e.shiftKey&&!window.matchMedia('(pointer: coarse)').matches))){e.preventDefault();void send()}if(e.key==='Escape'&&snapshot?.activeRunId){e.preventDefault();void stop()}};
  const chatSection=<section className="chat-panel"><div className="chat-heading"><div><span className="eyebrow">CONVERSATION</span><h2 title={selected?.name}>{selected?.name??'Your next idea starts here'}</h2></div><div className="run-badge" role="status"><button className="prompt-history-trigger" aria-label="Open prompt history" aria-expanded={promptHistoryOpen} disabled={!promptHistory.length} onClick={()=>{setPromptHistoryOpen(v=>!v);setPromptHistoryLimit(80)}}>Instructions · {promptHistory.length}</button>{running>0&&<span className="stat-chip live">{running} running</span>}{!!snapshot?.execution.failedCount&&<span className="stat-chip danger">{snapshot.execution.failedCount} failed</span>}{blocked>0&&<span className="stat-chip warn">{blocked} blocked</span>}{!!snapshot?.execution.decisionCount&&<span className="stat-chip warn">{snapshot.execution.decisionCount} decision needed</span>}{!running&&!snapshot?.execution.failedCount&&!blocked&&!snapshot?.execution.decisionCount&&<span className="stat-chip calm">All clear</span>}</div></div>
    <div className="session-controls"><label>Model<select aria-label="Model" value={options?.model?`${options.model.provider}::${options.model.id}`:''} disabled={!session||!options||optionsBusy||sending||!!snapshot?.activeRunId} onChange={e=>{const choice=options?.models.find(m=>`${m.provider}::${m.id}`===e.target.value);if(choice)void changeModel(choice.provider,choice.id)}}><option value="">{options?.models.length?'Select a model':'No models available'}</option>{options?.models.map(m=><option key={`${m.provider}::${m.id}`} value={`${m.provider}::${m.id}`}>{m.provider} / {m.name}</option>)}</select></label><label>Thinking<select aria-label="Thinking" value={options?.thinkingLevel??''} disabled={!session||!options||optionsBusy||sending||!!snapshot?.activeRunId} onChange={e=>void changeThinking(e.target.value)}><option value="">—</option>{options?.thinkingLevels.map(level=><option key={level} value={level}>{level}</option>)}</select></label><div className="context-usage" aria-label="Context usage"><span>Context <b>{typeof options?.contextUsage?.percent==='number'?`${Math.round(options.contextUsage.percent)}%`:'—'}</b></span>{typeof options?.contextUsage?.percent==='number'?<><progress aria-label="Context usage percentage" value={Math.max(0,Math.min(100,options.contextUsage.percent))} max="100"/><small>{options.contextUsage.tokens?.toLocaleString()??'—'} / {options.contextUsage.contextWindow.toLocaleString()} tokens</small></>:<small>Measured after a response</small>}</div></div>
    {!!activity.find(item=>item.sessionId===session)?.work.filter(w=>['running','waiting','blocked'].includes(w.status)).length&&<div className="live-work" role="status" aria-label="Current subagents and tasks">{activity.find(item=>item.sessionId===session)?.work.filter(w=>['running','waiting','blocked'].includes(w.status)).slice(0,4).map(w=><span key={w.id}>{w.kind}: {w.label} · {w.status}{w.action?` · ${w.action}`:''}</span>)}</div>}
    {promptHistoryOpen&&<div className="prompt-history" role="region" aria-label="Prompt history"><div className="prompt-history-heading"><strong>Instructions in this session</strong><button aria-label="Close prompt history" onClick={()=>setPromptHistoryOpen(false)}>✕</button></div><div className="prompt-history-list">{promptHistory.slice(-promptHistoryLimit).reverse().map((item,index)=><button key={item.id} onClick={()=>jumpToPrompt(item.id)}><span>#{promptHistory.length-index}</span><span>{item.text.replace(/\s+/g,' ').slice(0,110)}</span>↗</button>)}{promptHistory.length>promptHistoryLimit&&<button onClick={()=>setPromptHistoryLimit(v=>v+80)}>Show earlier instructions</button>}</div></div>}
    <div className="chat" aria-label="Chat output" ref={chatRef} onScroll={e=>{const el=e.currentTarget;followRef.current=el.scrollHeight-el.scrollTop-el.clientHeight<85;if(followRef.current)setNewContent(false)}}>{snapshot?.chat.length?snapshot.chat.map((m,index)=><ChatItem key={m.id} message={m} activityLabel={index===snapshot.chat.length-1&&snapshot.activeRunId?activityLabel:undefined}/>):<div className="chat-empty"><span className="empty-glyph" aria-hidden="true">›_</span><h3>{kitStatus.job ? 'Orchestrator runs separately' : session?'A fresh conversation':'Make space for what’s next'}</h3><p>{kitStatus.job ? 'Follow the kit run and its task status in Execution. It does not add messages to Pi chat.' : session?'Start with a question, a task or a piece of code. Pi will keep the thread here.':'Choose a workspace and start a session to work with Pi.'}</p></div>}{snapshot?.activeRunId&&(!snapshot.chat.length||snapshot.chat.at(-1)?.role!=='assistant'||!!snapshot.chat.at(-1)?.text)&&<div className="chat-processing" role="status">{activityLabel}</div>}</div>
    {newContent&&<button className="jump" onClick={()=>{followRef.current=true;chatRef.current?.scrollTo({top:chatRef.current.scrollHeight,behavior:'smooth'});setNewContent(false)}}>New content · Jump to bottom</button>}
    <div className="composer-dock"><div className="quick-row">{quickPrompts.map((value,index)=><button key={index} title={value} onClick={()=>usePrompt(value)}>{value}</button>)}<button aria-label="Edit saved shortcuts" onClick={()=>{setQuickDraft(quickPrompts.join('\n'));setEditPrompts(v=>!v)}}>Edit prompts</button></div>
      {editPrompts&&<div className="quick-editor"><label>Quick prompts (one per line, insert only)<textarea aria-label="Quick prompts" value={quickDraft} onChange={e=>setQuickDraft(e.target.value)}/></label><button onClick={()=>void savePrompts()}>Save prompts</button></div>}
      <label className="execution-target">Send with <select aria-label="Send with" value={executionTarget} onChange={e=>{setExecutionTarget(e.target.value as 'pi'|'kit');setAttachments([])}}><option value="pi">Pi (direct)</option><option value="kit" disabled={!kitStatus.available}>ludi-agent-kit orchestrator{kitStatus.available?'':' (not installed)'}</option></select></label>
      {executionTarget==='kit'&&<small className="kit-hint">Starts a separate kit run using this workspace. Kit model routing and costs apply. Results appear in Execution; Stop does not cancel a kit run.</small>}
      {executionTarget==='pi'&&<div className="attachment-tools"><input ref={attachRef} className="attach-input" aria-label="Choose files" type="file" multiple accept="image/png,image/jpeg,image/gif,image/webp,text/*,.txt,.md,.json,.ts,.tsx,.js,.jsx,.css,.html,.xml,.yaml,.yml,.py,.go,.rs,.ps1,.sh,.log,.csv,.svg,.c,.h,.cpp,.hpp,.java,.rb,.swift,.kt,.toml,.ini,.sql,.vue,.svelte" onChange={e=>addAttachments(e.target.files)}/><button className="attach-button" disabled={!session||!!snapshot?.activeRunId||sending} onClick={()=>attachRef.current?.click()}>＋ Attach files</button><span>Text and images · up to 4</span></div>}
      {!!attachments.length&&<div className="attachment-list" aria-label="Attached files">{attachments.map((file,i)=><span key={`${file.name}-${i}`} className="attachment-chip" title={file.name}>{file.name}<button aria-label={`Remove ${file.name}`} onClick={()=>{setAttachments(old=>old.filter((_,index)=>index!==i));setAttachmentError('')}}>×</button></span>)}</div>}
      {attachmentError&&<span className="attachment-error" role="alert">{attachmentError}</span>}
      <label className="composer-label">Prompt<textarea ref={composerRef} aria-label="Prompt" placeholder="Ask Pi about this workspace…" value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={onComposerKey} disabled={!session||!!snapshot?.activeRunId||!!kitStatus.job?.running||sending}/></label>
      <div className="composer-actions"><span>{kitStatus.job?.running?'Kit run in progress · cannot stop here':snapshot?.activeRunId?'Pi is working · Stop to edit':'Enter to send  ·  Shift+Enter for a line break'}</span><button className="button-primary" disabled={!session||(!prompt.trim()&&(executionTarget==='kit'||!attachments.length))||!!snapshot?.activeRunId||!!kitStatus.job?.running||sending||!server} onClick={()=>void send()}>Send <span aria-hidden="true">↗</span></button><button className="stop" disabled={!snapshot?.activeRunId} onClick={()=>void stop()}>Stop</button></div>
    </div>
  </section>;
  return <><main className={`app-shell view-${mobileView}`}><header className="app-header"><div className="brand"><span className="brand-mark" aria-hidden="true">›_</span><div><h1>pi-console</h1><span className="brand-subtitle">Your development space</span></div></div><div className="header-actions">{!!visibleActivity.length&&<button className="activity-trigger" aria-label="Active session alerts" onClick={()=>{navigate('workspaces');requestAnimationFrame(()=>document.querySelector('.activity-inbox')?.scrollIntoView({block:'start'}))}}>{needsInput?`⚠ ${needsInput}`:''}{needsInput&&activeCount?' · ':''}{activeCount?`● ${activeCount}`:''}{completedCount?`${needsInput||activeCount?' · ':''}✓ ${completedCount}`:''}</button>}<button className="settings-trigger" onClick={()=>navigate('settings')} aria-label="Open settings">⚙ <span>{preferences.language==='ja'?'設定':'Settings'}</span></button><span className="connection" role="status" aria-label="connection" data-connected={status==='Runtime healthy'} data-warning={/failed|unavailable|offline|reconnecting/i.test(status)}><span className="connection-dot" aria-hidden="true"/>{status}</span></div></header>
    {(error||!server||snapshot?.runtime==='failed'||failures)&&<div className="alerts">
      {(error||!server)&&<section className="error-card" role="alert"><b>{server?'Something needs your attention':'Server unavailable'}</b><p>{error||'The server is not responding. Pi state is unknown.'}</p><div className="error-actions"><button onClick={()=>{void refreshWorkspaces();if(session)reopen()}}>Reconnect / retry</button>{!['localhost','127.0.0.1'].includes(location.hostname)&&<button onClick={()=>location.assign('/')}>Reload / Access sign-in</button>}</div></section>}
      {snapshot?.runtime==='failed'&&<section className="error-card"><b>Pi process stopped unexpectedly</b><p>The run was interrupted. Reopen this session to continue safely.</p><button onClick={()=>void reopen()}>Reopen session</button></section>}
      {failures&&<div className="issue-notice"><details className="issue-card"><summary>Recent issue · {String(failures.payload.summary??failures.type)}</summary><p>{failures.type} · {failures.status??'status unknown'}. Retryability was not confirmed; inspect Activity for context.</p><details><summary>Technical details</summary><code>{failures.sourceRef?.kind??failures.source} · {failures.entityId}</code></details>{lastSubmitted&&<button onClick={()=>{setPrompt(lastSubmitted);navigate('chat')}}>Restore last prompt</button>}</details><button className="issue-dismiss" aria-label="Dismiss recent issue" onClick={()=>dismissIssue(failures.eventId)}>×</button></div>}
    </div>}
    {!!visibleActivity.length&&mobileView!=='settings'&&<section className="activity-inbox" aria-label="Activity notifications"><div className="activity-inbox-heading"><strong>Activity</strong><span>{needsInput} need input · {activeCount} running · {completedCount} finished</span></div><div className="activity-inbox-list">{visibleActivity.map(item=><div className="activity-card" key={item.sessionId}><button onClick={()=>openActive(item)}><span className="activity-inbox-name"><b>{item.sessionName}</b><small>{item.workspaceName}</small>{item.work.slice(0,4).map(w=><small key={w.id}>{w.kind}: {w.label} · {w.status}{w.action?` · ${w.action}`:''}</small>)}</span><span className="activity-inbox-status">{item.decisionCount>0&&<em>{item.decisionCount} need input</em>}{item.running&&<em className="is-running">Running</em>}{item.completion&&!dismissed.includes(item.completion.id)&&<em>{item.completion.status} · {new Date(item.completion.at).toLocaleTimeString()}</em>}</span></button>{item.completion&&!dismissed.includes(item.completion.id)&&<button className="activity-dismiss" aria-label={`Dismiss ${item.sessionName} completion`} onClick={()=>dismissCompletion(item.completion!.id)}>×</button>}</div>)}</div></section>}
    {(mobileView==='chat'||mobileView==='execution')&&<div className="session-toolbar"><button onClick={()=>navigate('sessions')}>{preferences.language==='ja'?'← セッション':'← Sessions'}</button><span title={`${current?.name??''} / ${selected?.name??'New conversation'}`}>{current?.name} <span aria-hidden="true">/</span> {selected?.name??'New conversation'}</span></div>}
    {mobileView==='settings'?<SettingsPage preferences={preferences} onChange={updatePreferences} onBack={()=>{if(history.state?.fromConsole)history.back();else navigate('workspaces')}} workspaceCount={workspaces.length} sessionCount={sessions.length} connected={server&&online} availableModels={options?.models}/>:<div className="console-layout"><aside className="sidebar"><section className="workspace-hub"><span className="eyebrow">YOUR SPACE</span><div className="section-heading"><h2>Workspaces</h2></div><p>Choose an existing workspace to see its sessions.</p><input aria-label="Find workspace" placeholder="Find workspace…" value={workspaceQuery} onChange={e=>setWorkspaceQuery(e.target.value)}/><div className="workspace-hub-list">{availableWorkspaces.length?availableWorkspaces.map(w=><button key={w.id} className="workspace-card" onClick={()=>void switchWorkspace(w.id)}><span className="workspace-card-icon" aria-hidden="true">{w.pinned?'★':'⌘'}</span><span><b>{w.name}</b><small title={w.path}>{w.path}</small><small>Last opened {new Date(w.lastOpenedAt).toLocaleString()}</small>{activity.filter(a=>a.workspaceId===w.id).map(a=><small className="workspace-activity" key={a.sessionId}>{a.decisionCount>0?`${a.decisionCount} need input · `:''}{a.running?'Running · ':''}{a.sessionName}</small>)}</span><span aria-hidden="true">›</span></button>):<p className="session-empty">{workspaceQuery?'No matching workspaces.':'No workspaces yet. Add one below.'}</p>}</div>{unavailableWorkspaces.length>0&&<details className="unavailable-workspaces"><summary>Unavailable paths · {unavailableWorkspaces.length}</summary>{unavailableWorkspaces.map(w=><p key={w.id} title={w.path}>{w.name} · {w.path} <button aria-label={`Remove ${w.name} from Pi Console`} onClick={()=>void removeWorkspace(w)}>Remove</button></p>)}</details>}</section><section className={`workspace-bar ${current?'has-workspace':''} ${workspaceTools?'expanded':''}`}><div className="workspace-create-heading"><span className="eyebrow">NEW WORKSPACE</span><h2>Add a workspace</h2><p>Choose a folder on this server, or enter its path.</p></div><div className="section-heading"><span className="eyebrow">WORKSPACE</span>{current&&<span className="workspace-symbol" aria-hidden="true">⌘</span>}</div><h2>{current?.name??'Choose a workspace'}</h2><p className="workspace-path" title={current?.path}>{current?.path??'Your workspaces live here.'}</p>
      <div className="workspace-select"><input aria-label="Filter workspaces" placeholder="Filter workspaces" value={workspaceQuery} onChange={e=>setWorkspaceQuery(e.target.value)}/><select aria-label="Workspace" value={workspace} onChange={e=>void switchWorkspace(e.target.value)}><option value="">Select workspace</option>{(['pinned','recent','all'] as const).map(kind=><optgroup label={kind[0].toUpperCase()+kind.slice(1)} key={kind}>{groups[kind].map(w=><option key={w.id} value={w.id} disabled={w.valid===false}>{w.pinned?'★ ':''}{w.name}{w.valid===false?' — path missing':''}</option>)}</optgroup>)}</select></div>
      <div className="workspace-actions"><label>New workspace path<input aria-label="Workspace path" placeholder="C:\\Dev\\my-app" value={path} onChange={e=>setPath(e.target.value)}/></label><div className="workspace-action-row"><button ref={browseTrigger} className="button-subtle" onClick={()=>setBrowseOpen(true)}>Browse folders</button><button className="button-primary" onClick={()=>void addWorkspace()}><span className="desktop-label">Open Workspace</span><span className="mobile-label">Add & open</span></button></div></div>
      {current&&<button className="manage-toggle" aria-expanded={workspaceTools} onClick={()=>setWorkspaceTools(v=>!v)}>{workspaceTools?'Hide workspace tools':<><span className="desktop-label">Manage workspace</span><span className="mobile-label">Edit selected workspace</span></>} <span aria-hidden="true">⌄</span></button>}
      {current&&<div className="workspace-management"><strong className="workspace-management-title">Edit selected workspace · {current.name}</strong><input aria-label="Rename workspace" value={workspaceName} onChange={e=>setWorkspaceName(e.target.value)}/><button onClick={()=>void updateWorkspace({name:workspaceName})}>Rename</button><button onClick={()=>void updateWorkspace({pinned:!current.pinned})}>{current.pinned?'Unpin':'Pin'}</button><button className="workspace-remove" onClick={()=>void removeWorkspace(current)}>Remove workspace</button><small>Last opened {new Date(current.lastOpenedAt).toLocaleString()}</small></div>}
      </section><section className="session-panel"><button className="back-link" onClick={()=>navigate('workspaces')}>{preferences.language==='ja'?'← ワークスペース':'← Workspaces'}</button><div className="session-context"><span className="eyebrow">IN WORKSPACE</span><strong>{current?.name??'Choose a workspace'}</strong></div><div className="section-heading"><h2>Sessions</h2><button className="new-session" disabled={!workspace||current?.valid===false} onClick={()=>void newSession()} aria-label="New Session">＋ <span>New Session</span></button></div><input ref={searchRef} aria-label="Search sessions" placeholder="Search sessions…" value={sessionQuery} onChange={e=>setSessionQuery(e.target.value)}/><div className="session-list" aria-label="Session list">{visibleSessions.length?visibleSessions.map(s=><div key={s.id} className="session-row"><button className={s.id===session?'current':''} onClick={()=>chooseSession(s.id)}><span className="session-dot" data-running={!!s.running} data-needs-input={!!s.decisionCount} aria-hidden="true"/><span className="session-copy"><b>{s.name??'New conversation'}</b><span>{s.decisionCount?`${s.decisionCount} need input · `:''}{s.running?'Running · ':''}{s.updatedAt?new Date(s.updatedAt).toLocaleString():'Just created'}</span></span></button><button className="session-recycle" aria-label={`Move ${s.name??'New conversation'} to Recycle Bin`} title="Move to Windows Recycle Bin" disabled={!!s.running||!!s.decisionCount} onClick={()=>void recycleSession(s)}>🗑</button></div>):<p className="session-empty">{workspace?(sessionQuery?'No matching sessions.':'No sessions yet. Start one above.'):'Select a workspace first.'}</p>}</div>
      <label className="session-switcher">Current session<select aria-label="Session" value={session} onChange={e=>chooseSession(e.target.value)}><option value="">Select session</option>{visibleSessions.map(s=><option key={s.id} value={s.id}>{s.name??`New conversation${s.updatedAt?` · ${new Date(s.updatedAt).toLocaleTimeString()}`:''}`}</option>)}</select></label><div className="runtime-line">Pi process <strong aria-label="runtime state">{snapshot?.runtime??'stopped'}</strong></div></section></aside>
      <div className="content-pane">{chatSection}<div className="execution-area">{kitStatus.job&&<KitRunCard job={kitStatus.job} nodes={snapshot?.execution.nodes??[]}/>}<ExecutionPanel state={snapshot?.execution} events={executionEvents} focusRootId={kitStatus.job?.runId ? `orchestrator:${kitStatus.job.runId}` : undefined}/></div></div></div>}
    {(mobileView==='chat'||mobileView==='execution')&&<nav className="mobile-nav" aria-label="Session views"><button onClick={()=>navigate('chat')} aria-current={mobileView==='chat'?'page':undefined}>Chat</button><button onClick={()=>navigate('execution')} aria-current={mobileView==='execution'?'page':undefined}>Execution · {running}{snapshot?.execution.failedCount?` !${snapshot.execution.failedCount}`:''}{snapshot?.execution.decisionCount?` ?${snapshot.execution.decisionCount}`:''}</button></nav>}
  </main>{preferences.petEnabled&&<PetWidget preferences={preferences} snapshot={snapshot} view={mobileView}/>}{browseOpen&&<DirectoryPicker initialPath={path.trim()||current?.path||''} onSelect={folder=>{setPath(folder);setBrowseOpen(false);requestAnimationFrame(()=>browseTrigger.current?.focus())}} onClose={()=>{setBrowseOpen(false);requestAnimationFrame(()=>browseTrigger.current?.focus())}}/>}</>;
}
if('serviceWorker' in navigator)window.addEventListener('load',()=>{void navigator.serviceWorker.register('/sw.js').catch(()=>{})});
createRoot(document.getElementById('root')!).render(<App/>);
