import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import type { ExecutionEvent, Snapshot, Workspace, SessionInfo, SessionOptions, PromptAttachment, ActiveSessionSummary, QueuedItem } from '../shared/types.ts';
import ExecutionPanel from './ExecutionPanel.tsx';
import ConversationStatus from './ConversationStatus.tsx';
import ModelSettingsDialog from './ModelSettingsDialog.tsx';
import WorkspaceMenu from './WorkspaceMenu.tsx';
import SessionItemMenu from './SessionItemMenu.tsx';
import QueueDisclosure from './QueueDisclosure.tsx';
import { conversationStatus } from './conversation-status.ts';
import ChatItem from './ChatMessage.tsx';
import MarkdownContent from './MarkdownContent.tsx';
import DirectoryPicker from './DirectoryPicker.tsx';
import SettingsPage from './SettingsPage.tsx';
import KitRunCard, { type KitJob } from './KitRunCard.tsx';
import KitDecisionPanel, { type KitDecisions } from './KitDecisionPanel.tsx';
import KitChatReport from './KitChatReport.tsx';
import PetWidget from './PetWidget.tsx';
import VoiceInput from './VoiceInput.tsx';
import { loadPreferences, savePreferences } from './preferences.ts';
import type { ConsolePreferences } from './preferences.ts';
import { acceptSnapshot, connectionLabel, filterSessions, groupWorkspaces, issueToastDurationMs, recentIssue, validQuickPrompts } from './ui-logic.ts';
import { decodeUtf8 } from '../shared/attachments.ts';
import { freshCompletions, notifiedCompletionIds } from './notification-logic.ts';
import './style.css';
import { liveExecutionNodes } from '../shared/execution-activity.ts';
import { loadComposerDraft, readComposerDraft, composerDraftRevision, adoptComposerDraftRevision, saveComposerDraft, subscribeComposerDrafts, DraftConflictError, type ComposerDraft, type PendingSubmission } from './composer-drafts.ts';
const jsonResponse = async (r:Response) => {
  if(!r.headers.get('content-type')?.includes('application/json')) throw Error('Connection lost or Access sign-in required. Reload this page to sign in.');
  const data=await r.json();if(!r.ok) throw Error(r.status===401?'Cloudflare Access sign-in required. Reload this page.':data.error??`HTTP ${r.status}`);return data;
};
const get = async (url: string) => jsonResponse(await fetch(url,{cache:'no-store'}));
const completionLabel = (completion: NonNullable<ActiveSessionSummary['completion']>) => completion.scope === 'conversation' ? 'Conversation' : completion.scope === 'kit' ? 'Kit run' : 'Subagent';
const post = async (url: string, value: object) => jsonResponse(await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(value) }));
function App() {
  const [workspaces, setWorkspaces] = useState<Workspace[]>([]); const [workspace,setWorkspace]=useState(''); const [path,setPath]=useState('');
  const [workspaceQuery,setWorkspaceQuery]=useState(''); const [workspaceName,setWorkspaceName]=useState('');const [workspaceTools,setWorkspaceTools]=useState(false);
  const [workspaceBusy,setWorkspaceBusy]=useState<''|'add'|'rename'|'pin'|'remove'>('');const [addWorkspaceOpen,setAddWorkspaceOpen]=useState(false);
  const [explorerBusy,setExplorerBusy]=useState(false);const [explorerNotice,setExplorerNotice]=useState<{id:string;text:string;error:boolean}>();const renameScope=useRef('');const renameDirty=useRef(false);
  const [browseOpen,setBrowseOpen]=useState(false);const browseTrigger=useRef<HTMLButtonElement>(null);
  const [sessions,setSessions]=useState<SessionInfo[]>([]);const [session,setSession]=useState('');const [sessionQuery,setSessionQuery]=useState('');
  const [creatingSession,setCreatingSession]=useState(false);const creatingSessionRef=useRef(false);
  const [activity,setActivity]=useState<ActiveSessionSummary[]>([]);const seenCompletions=useRef<Set<string>|undefined>(undefined);
  const [dismissed,setDismissed]=useState<string[]>(()=>{try{const value=JSON.parse(localStorage.getItem('pi-console-dismissed-completions')??'[]');return Array.isArray(value)?value.filter((s:unknown)=>typeof s==='string').slice(-200):[]}catch{return []}});
  const [dismissedIssues,setDismissedIssues]=useState<string[]>(()=>{try{const value=JSON.parse(localStorage.getItem('pi-console-dismissed-issues')??'[]');return Array.isArray(value)?value.filter((s:unknown)=>typeof s==='string').slice(-200):[]}catch{return []}});
  const [issueTick,setIssueTick]=useState(0);
  const [issueHold,setIssueHold]=useState<{eventId:string;until:number}>();const issueToastRef=useRef<HTMLElement>(null);const issuePointerInside=useRef(false);
  const syncIssueHold=(eventId:string)=>{const toast=issueToastRef.current;const busy=issuePointerInside.current||!!toast?.querySelector('details[open]')||!!toast?.contains(document.activeElement);setIssueHold({eventId,until:busy?Infinity:Date.now()+issueToastDurationMs})};
  const [focusedIssue,setFocusedIssue]=useState<{workspaceId:string;sessionId:string;eventId:string}>();
  const dismissIssue=(id:string)=>setDismissedIssues(old=>{const next=[...old.filter(x=>x!==id),id].slice(-200);localStorage.setItem('pi-console-dismissed-issues',JSON.stringify(next));return next});
  const dismissCompletion=(id:string)=>{setDismissed(old=>{const next=[...old.filter(x=>x!==id),id].slice(-200);localStorage.setItem('pi-console-dismissed-completions',JSON.stringify(next));return next})};
  const [promptHistoryOpen,setPromptHistoryOpen]=useState(false);const [promptHistoryLimit,setPromptHistoryLimit]=useState(80);
  const [storedSnapshot,setSnapshot]=useState<Snapshot>();
  // Never display or act on another session while its replacement is loading.
  const snapshot=storedSnapshot?.session.id===session&&storedSnapshot.session.workspaceId===workspace?storedSnapshot:undefined;
  const [executionEvents,setExecutionEvents]=useState<ExecutionEvent[]>([]);
  const [executionExpanded,setExecutionExpanded]=useState(false);
  const draftScope=workspace&&session?JSON.stringify([workspace,session]):'';
  const [composerDrafts,setComposerDrafts]=useState<Record<string,ComposerDraft>>({});
  const composerDraftsRef=useRef(composerDrafts);const draftWrites=useRef(0);const draftRevisions=useRef<Record<string,number>>({});const failedDraftScopes=useRef(new Set<string>());const unreadableDraftScopes=useRef(new Set<string>());
  const [draftWarning,setDraftWarning]=useState('');
  const dirtyDraftScopes=useRef(new Set<string>());const conflictedDraftScopes=useRef(new Set<string>());const [draftConflicts,setDraftConflicts]=useState<string[]>([]);
  const markDraftConflict=(scope:string)=>{conflictedDraftScopes.current.add(scope);setDraftConflicts([...conflictedDraftScopes.current])};
  const draftConflict=draftConflicts.includes(draftScope);
  const draftLoaded=!!draftScope&&Object.hasOwn(composerDrafts,draftScope);
  const prompt=composerDrafts[draftScope]?.text??'';const attachments=composerDrafts[draftScope]?.files??[];
  const pendingSubmission=composerDrafts[draftScope]?.submission;
  const updateComposerDraft=(scope:string,update:(draft:ComposerDraft)=>ComposerDraft)=>{
    if(!scope||!Object.hasOwn(composerDraftsRef.current,scope))return Promise.reject(Error('Draft is not loaded'));
    const draft=update(composerDraftsRef.current[scope]);composerDraftsRef.current={...composerDraftsRef.current,[scope]:draft};setComposerDrafts(composerDraftsRef.current);
    const revision=draftRevisions.current[scope]=(draftRevisions.current[scope]??0)+1;draftWrites.current++;dirtyDraftScopes.current.add(scope);
    // Do not overwrite an unreadable stored draft with an empty/default record.
    const saved=unreadableDraftScopes.current.has(scope)?Promise.reject(Error('Stored draft unreadable')):saveComposerDraft(scope,draft);
    void saved.then(()=>{if(draftRevisions.current[scope]===revision){dirtyDraftScopes.current.delete(scope);failedDraftScopes.current.delete(scope);if(!failedDraftScopes.current.size)setDraftWarning('')}})
      .catch(error=>{if(error instanceof DraftConflictError)markDraftConflict(scope);if(draftRevisions.current[scope]===revision){failedDraftScopes.current.add(scope);setDraftWarning('Draft could not be saved on this device. Keep this page open: unsaved input may be lost or sent input may reappear after reload.')}})
      .finally(()=>{draftWrites.current--});
    return saved;
  };
  const setPrompt=(value:React.SetStateAction<string>)=>{void updateComposerDraft(draftScope,draft=>({...draft,text:typeof value==='function'?value(draft.text):value})).catch(()=>{})};
  const setAttachments=(value:React.SetStateAction<File[]>)=>{void updateComposerDraft(draftScope,draft=>({...draft,files:typeof value==='function'?value(draft.files):value})).catch(()=>{})};
  useEffect(()=>{if(!draftScope||Object.hasOwn(composerDraftsRef.current,draftScope))return;
    const scope=draftScope;void loadComposerDraft(scope).catch(()=>{unreadableDraftScopes.current.add(scope);setDraftWarning('Stored draft could not be loaded on this device. Keep this page open to protect new input.');return {text:'',files:[]} as ComposerDraft}).then(draft=>{
      if(Object.hasOwn(composerDraftsRef.current,scope))return;
      composerDraftsRef.current={...composerDraftsRef.current,[scope]:draft};setComposerDrafts(composerDraftsRef.current);
    });
  },[draftScope]);
  const refreshDraft=async(scope:string,replaceLocal=false)=>{
    if(!Object.hasOwn(composerDraftsRef.current,scope))return;
    if(!replaceLocal&&conflictedDraftScopes.current.has(scope))return;
    const revision=draftRevisions.current[scope]??0;
    try{const value=await readComposerDraft(scope);if((draftRevisions.current[scope]??0)!==revision)return;
      const recoveredUnreadable=unreadableDraftScopes.current.delete(scope);
      if(!replaceLocal&&dirtyDraftScopes.current.has(scope)){
        if(recoveredUnreadable){
          // An unseen recovered draft must not be overwritten by local input.
          if(value.draft.text||value.draft.files.length||value.draft.submission){markDraftConflict(scope);return}
          adoptComposerDraftRevision(scope,value.revision);await updateComposerDraft(scope,draft=>draft);
        }else if(value.revision!==composerDraftRevision(scope))markDraftConflict(scope);
        return;
      }
      adoptComposerDraftRevision(scope,value.revision);composerDraftsRef.current={...composerDraftsRef.current,[scope]:value.draft};setComposerDrafts(composerDraftsRef.current);
      dirtyDraftScopes.current.delete(scope);conflictedDraftScopes.current.delete(scope);failedDraftScopes.current.delete(scope);setDraftConflicts([...conflictedDraftScopes.current]);if(!failedDraftScopes.current.size)setDraftWarning('');
    }catch{setDraftWarning('Draft refresh failed. Keep this page open to protect local input.')}
  };
  useEffect(()=>subscribeComposerDrafts(scope=>{for(const key of scope?[scope]:Object.keys(composerDraftsRef.current))void refreshDraft(key)}),[]);
  const reloadSavedDraft=()=>{if(window.confirm('Replace this tab’s input with the latest saved draft? Copy any unsaved local input first.'))void refreshDraft(draftScope,true)};
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(draftWrites.current||failedDraftScopes.current.size){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[]);
  const [lastSubmitted,setLastSubmitted]=useState('');
  const [coarsePointer,setCoarsePointer]=useState(()=>window.matchMedia('(pointer: coarse)').matches);
  useEffect(()=>{const query=window.matchMedia('(pointer: coarse)');const changed=()=>setCoarsePointer(query.matches);query.addEventListener('change',changed);return()=>query.removeEventListener('change',changed)},[]);
  const [busyMode,setBusyMode]=useState<'followUp'|'steer'>('followUp');
  // Per-item edit drafts for the console-owned follow-up queue; a draft captures the
  // revision it loaded so Save is a compare-and-swap against concurrent edits/dispatch.
  const [queueDrafts,setQueueDrafts]=useState<Record<string,{text:string;revision:number}>>({});
  const [queueBusyScopes,setQueueBusyScopes]=useState<Record<string,boolean>>({});
  const queueBusy=!!queueBusyScopes[`${workspace}:${session}`];
  const setQueueBusy=(scope:string,busy:boolean)=>setQueueBusyScopes(old=>{const next={...old};if(busy)next[scope]=true;else delete next[scope];return next});
  const [kitRequest,setKitRequest]=useState('');
  const [kitStatus,setKitStatus]=useState<{available:boolean;job?:KitJob}>({available:false});
  const [kitDecisions,setKitDecisions]=useState<{scope:string;data:KitDecisions}>();const decisionScope=useRef('');decisionScope.current=`${workspace}:${session}`;
  const [pausedChatAllowed,setPausedChatAllowed]=useState('');
  const [options,setOptions]=useState<SessionOptions>();const [optionsBusy,setOptionsBusy]=useState(false);
  const [attachmentError,setAttachmentError]=useState('');
  const [sendingScopes,setSendingScopes]=useState<Record<string,boolean>>({});const sendingScopesRef=useRef(new Set<string>());
  const [recyclingScopes,setRecyclingScopes]=useState<Record<string,boolean>>({});const recyclingScopesRef=useRef(new Set<string>());
  const [recycleErrors,setRecycleErrors]=useState<Record<string,string>>({});
  const recycling=!!recyclingScopes[draftScope];
  const sending=!!sendingScopes[draftScope];
  const setSending=(scope:string,busy:boolean)=>{
    if(busy)sendingScopesRef.current.add(scope);else sendingScopesRef.current.delete(scope);
    setSendingScopes(old=>{const next={...old};if(busy)next[scope]=true;else delete next[scope];return next});
  };
  const attachRef=useRef<HTMLInputElement>(null);
  const [error,setError]=useState('');const [sse,setSse]=useState<'offline'|'connecting'|'connected'|'reconnecting'>('offline');
  type FilePreview={path:string;line?:number;content?:string;format?:'markdown'|'text'|'code'|'image'|'video';mediaUrl?:string;error?:string};
  const [filePreview,setFilePreview]=useState<FilePreview>();const [fileCopyStatus,setFileCopyStatus]=useState('');const [fileHistory,setFileHistory]=useState<FilePreview[]>([]);const fileRequest=useRef(0);const fileCloseRef=useRef<HTMLButtonElement>(null);const fileDialogRef=useRef<HTMLDialogElement>(null);const fileInvoker=useRef<{element?:HTMLElement;messageId?:string;linkIndex:number}>({linkIndex:-1});
  const [server,setServer]=useState(true);const [online,setOnline]=useState(navigator.onLine);
  type View='workspaces'|'sessions'|'chat'|'execution'|'settings';
  const initial=useRef<{view:View;workspace:string;session:string}|null>(null);
  if(!initial.current){const state=history.state;const valid=['workspaces','sessions','chat','execution','settings'];initial.current=state?.piConsoleNav&&valid.includes(state.view)?{view:state.view,workspace:typeof state.workspace==='string'?state.workspace:'',session:typeof state.session==='string'?state.session:''}:{view:new URLSearchParams(location.search).get('view')==='settings'?'settings':'workspaces',workspace:'',session:''}}
  const start=initial.current;
  const [mobileView,setMobileView]=useState<View>(start.view);
  const [sessionReturn,setSessionReturn]=useState<'sessions'|'workspaces'>(history.state?.sessionReturn==='workspaces'?'workspaces':'sessions');
  const [preferences,setPreferences]=useState<ConsolePreferences>(loadPreferences);const notificationsEnabled=useRef(preferences.completionNotifications);notificationsEnabled.current=preferences.completionNotifications;
  const [quickPrompts,setQuickPrompts]=useState<string[]>([]);const [editPrompts,setEditPrompts]=useState(false);const [quickDraft,setQuickDraft]=useState('');
  const [modelFilterOpen,setModelFilterOpen]=useState(false);const [modelSearch,setModelSearch]=useState('');const [modelProvider,setModelProvider]=useState('');const [compactControlsOpen,setCompactControlsOpen]=useState(false);
  const [compactScreen,setCompactScreen]=useState(()=>window.matchMedia('(max-width:900px)').matches);
  const [shortScreen,setShortScreen]=useState(()=>window.matchMedia('(max-width:900px) and (max-height:480px)').matches);
  useEffect(()=>{const query=window.matchMedia('(max-width:900px)'),short=window.matchMedia('(max-width:900px) and (max-height:480px)');const changed=()=>{setCompactScreen(query.matches);setCompactControlsOpen(false)};const shortChanged=()=>setShortScreen(short.matches);query.addEventListener('change',changed);short.addEventListener('change',shortChanged);changed();shortChanged();return()=>{query.removeEventListener('change',changed);short.removeEventListener('change',shortChanged)}},[]);
  useEffect(()=>{setCompactControlsOpen(false)},[mobileView]);
  const modelSearchRef=useRef<HTMLInputElement>(null);
  const [newContent,setNewContent]=useState(false);const [connectionEpoch,setConnectionEpoch]=useState(0);
  const ref=useRef<Snapshot|undefined>(undefined);const activityVersion=useRef(0);const refreshTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const chatRef=useRef<HTMLDivElement>(null);
  const followRef=useRef(true);const searchRef=useRef<HTMLInputElement>(null);const composerRef=useRef<HTMLTextAreaElement>(null);const workspaceCreateRef=useRef<HTMLHeadingElement>(null);const workspaceAddInvokerRef=useRef<HTMLButtonElement>(null);
  // Navigation generation: workspace/session changes invalidate in-flight async replies
  // started under the previous screen, so a slow A response can never write B's chat,
  // options, errors or busy flags. View-only moves (chat↔execution) share the same
  // session scope and keep the generation so the live SSE/refresh is not killed.
  const navEpoch=useRef(0);const navGen=()=>navEpoch.current;
  const workspaceSelection=useRef(0);
  const bumpNav=()=>{navEpoch.current++;setOptionsBusy(false);setCreatingSession(false);creatingSessionRef.current=false};
  const navigate=(view:View,nextWorkspace=workspace,nextSession=session,returnTo=sessionReturn)=>{if(view==='execution')setExecutionExpanded(true);const next={piConsoleNav:true,view,workspace:nextWorkspace,session:nextSession,sessionReturn:returnTo,...(view==='settings'?{fromConsole:true}:{})};if(view===mobileView&&nextWorkspace===workspace&&nextSession===session&&returnTo===sessionReturn)return;history.pushState(next,'',view==='settings'?'?view=settings':location.pathname);if(nextWorkspace!==workspace||nextSession!==session)bumpNav();setMobileView(view);setSessionReturn(returnTo);if(nextWorkspace!==workspace)setWorkspace(nextWorkspace);if(nextSession!==session)setSession(nextSession)};
  const updatePreferences=(value:ConsolePreferences)=>{setPreferences(value);savePreferences(value)};
  useEffect(()=>{document.documentElement.dataset.appearance=preferences.appearance},[preferences.appearance]);
  useEffect(()=>{document.documentElement.lang=preferences.language},[preferences.language]);

  useEffect(()=>{fileRequest.current++;setFilePreview(undefined);setFileHistory([]);setFileCopyStatus('')},[workspace,session]);
  const current=workspaces.find(w=>w.id===workspace);const selected=sessions.find(s=>s.id===session);
  // The rename draft belongs to the selected workspace: (re)seed it when the workspace
  // identity changes — switchWorkspace, browser back/forward and deep links all funnel
  // through `workspace` — so an async reply can never overwrite another selection's draft.
  // A mere name refresh (rename round-trip or external rename picked up by
  // refreshWorkspaces) syncs only a clean draft; an edited draft is preserved.
  useEffect(()=>{if(workspace!==renameScope.current){renameScope.current=workspace;renameDirty.current=false}if(!renameDirty.current)setWorkspaceName(current?.name??'')},[workspace,current?.name]);
  useEffect(()=>{setWorkspaceBusy('');if(current)setAddWorkspaceOpen(false)},[current?.id]);
  useEffect(()=>{if(!filePreview?.line||filePreview.content===undefined)return;const frame=requestAnimationFrame(()=>{const body=fileDialogRef.current?.querySelector<HTMLElement>('.file-preview-body');const row=body?.querySelector<HTMLElement>('.source-line-target');if(body&&row)body.scrollTop+=row.getBoundingClientRect().top-body.getBoundingClientRect().top-body.clientHeight/3});return()=>cancelAnimationFrame(frame)},[filePreview]);
  useEffect(()=>{if(!filePreview)return;const dialog=fileDialogRef.current!;const {element:previous,messageId,linkIndex}=fileInvoker.current;dialog.showModal();fileCloseRef.current?.focus();return()=>{dialog.close();requestAnimationFrame(()=>{if(previous?.isConnected)previous.focus();else if(messageId&&linkIndex>=0){const current=Array.from(chatRef.current?.querySelectorAll<HTMLElement>('[data-message-id]')??[]).find(el=>el.dataset.messageId===messageId);current?.querySelectorAll<HTMLElement>('.file-link')[linkIndex]?.focus()}})}},[!!filePreview]);
  useEffect(()=>{const initialState=start;setWorkspace(initialState.workspace);setSession(initialState.session);history.replaceState({piConsoleNav:true,...initialState,sessionReturn:history.state?.sessionReturn==='workspaces'?'workspaces':'sessions',...(history.state?.fromConsole?{fromConsole:true}:{})},'',location.href);const pop=(event:PopStateEvent)=>{const nav=event.state;if(!nav?.piConsoleNav)return;const nw=nav.workspace??'',ns=nav.session??'';if(`${nw}:${ns}`!==decisionScope.current){bumpNav();ref.current=undefined;setSnapshot(undefined);setExecutionEvents([]);setOptions(undefined);setKitStatus({available:false});setKitDecisions(undefined);setPromptHistoryOpen(false);setLastSubmitted('');followRef.current=true;if(nw!==decisionScope.current.split(':')[0])setSessions([])}setWorkspace(nw);setSession(ns);setSessionReturn(nav.sessionReturn==='workspaces'?'workspaces':'sessions');setMobileView(nav.view??'workspaces');if(nav.view==='execution')setExecutionExpanded(true)};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[]);
  const groups=useMemo(()=>groupWorkspaces(workspaces,workspaceQuery),[workspaces,workspaceQuery]);
  // A filter must never hide the workspace the user is actually working in.
  if(current&&!groups.pinned.concat(groups.recent,groups.all).some(w=>w.id===current.id))(current.pinned?groups.pinned:groups.recent).unshift(current);
  const availableWorkspaces=[...groups.pinned,...groups.recent,...groups.all].filter(w=>w.valid!==false);
  const unavailableWorkspaces=[...groups.pinned,...groups.recent,...groups.all].filter(w=>w.valid===false);
  const visibleSessions=useMemo(()=>filterSessions(sessions,sessionQuery),[sessions,sessionQuery]);
  const defaultPrompts=quickPrompts.length===3&&quickPrompts.every((text,i)=>text===['続きを実装して','テストして','原因を調べて'][i]);
  const displayedPrompts=defaultPrompts&&preferences.language==='en'?['Continue implementing','Run tests','Investigate the cause']:quickPrompts;
  const modelKey=(model:{provider:string;id:string})=>`${model.provider}::${model.id}`;
  const selectedModel=options?.model;const providerFilter=modelProvider||selectedModel?.provider||'';
  const selectedModelName=options?.models.find(m=>m.provider===selectedModel?.provider&&m.id===selectedModel.id)?.name??selectedModel?.id;
  const providers=[...new Set(options?.models.map(model=>model.provider)??[])];
  const matchingModels=options?.models.filter(model=>(providerFilter==='*'||model.provider===providerFilter)&&`${model.provider} ${model.name} ${model.id}`.toLowerCase().includes(modelSearch.trim().toLowerCase()))??[];
  const visibleModels=matchingModels.slice(0,80);
  if(selectedModel&&!visibleModels.some(model=>modelKey(model)===modelKey(selectedModel))){const current=options?.models.find(model=>modelKey(model)===modelKey(selectedModel));if(current)visibleModels.unshift(current)}
  const promptHistory=useMemo(()=>snapshot?.chat.filter(m=>m.role==='user')??[],[snapshot?.chat]);
  const visibleActivity=activity.filter(s=>(s.running||s.decisionCount||s.completion&&!dismissed.includes(s.completion.id)||s.work.some(w=>w.status==='waiting'||w.status==='blocked'))&&(!['chat','execution'].includes(mobileView)||s.sessionId!==session||s.workspaceId!==workspace));
  const needsInput=visibleActivity.filter(s=>s.decisionCount>0).length;const activeCount=visibleActivity.filter(s=>s.running).length;
  // Header ✓ counts only the actual conversation-level completion, not a finished
  // detached child or a kit sub-run while the Pi session itself is still running.
  const completedCount=visibleActivity.filter(s=>s.completion?.scope==='conversation'&&!s.running&&!s.decisionCount&&!dismissed.includes(s.completion.id)).length;
  const liveNodes=liveExecutionNodes(snapshot?.execution.nodes??[]);
  const status=!session&&server&&online?'Server ready · no Pi session':connectionLabel({online,server,sse,runtime:snapshot?.runtime});
  const running=liveNodes.filter(n=>n.status==='running').length;
  const executionRunning=Math.max(running,kitStatus.job?.running?1:0);
  const currentDecisions=kitDecisions?.scope===decisionScope.current?kitDecisions.data:undefined;
  const retryAvailable=!!currentDecisions?.canResume&&!currentDecisions.decisions.length;
  const chatAllowed=retryAvailable&&pausedChatAllowed===`${decisionScope.current}:${currentDecisions?.runId}`;
  const kitAwaiting=!!kitStatus.job?.needsInput||!!currentDecisions?.decisions.length||retryAvailable&&!chatAllowed;
  const kitBlocked=!!kitStatus.job?.running||kitAwaiting;
  const currentSnapshot=snapshot?.session.id===session&&snapshot.session.workspaceId===workspace?snapshot:undefined;
  const currentStatus=conversationStatus({selected:!!session,snapshot:currentSnapshot,sending,needsInput:kitAwaiting,kit:kitStatus.job});
  const failures=snapshot?.session.id===session&&snapshot.session.workspaceId===workspace?recentIssue(snapshot.events.filter(event=>event.sessionId===session&&event.workspaceId===workspace),dismissedIssues,Date.now(),issueHold):undefined;
  const executionAttention=!!currentSnapshot&&(kitAwaiting||!!currentSnapshot.execution.decisionCount||currentSnapshot.runtime==='failed'||!!failures||!!kitStatus.job?.reportError||!!kitStatus.job?.error);
  const executionAttentionLabel=currentStatus.kind==='needs-input'?'Input required':'Execution issue';
  const executionAttentionKey=executionAttention?JSON.stringify([draftScope,currentSnapshot?.runtime==='failed',currentSnapshot?.execution.decisionCount,kitAwaiting?currentDecisions?.runId??kitStatus.job?.runId:undefined,kitAwaiting?currentDecisions?.decisions.map(d=>d.id).sort():undefined,liveNodes.filter(n=>n.kind==='decision').map(n=>n.id).sort(),failures?.eventId,kitStatus.job?.reportError||kitStatus.job?.error?kitStatus.job?.runId:undefined,kitStatus.job?.reportError,kitStatus.job?.error]):'';
  useEffect(()=>{setExecutionExpanded(mobileView==='execution')},[draftScope]);
  useEffect(()=>{if(executionAttentionKey)setExecutionExpanded(true)},[executionAttentionKey]);
  useEffect(()=>{if(!failures)return;const until=issueHold?.eventId===failures.eventId?issueHold.until:Date.parse(failures.timestamp)+issueToastDurationMs;if(!Number.isFinite(until))return;const timer=setTimeout(()=>setIssueTick(value=>value+1),Math.max(0,until-Date.now())+30);return()=>clearTimeout(timer)},[failures?.eventId,issueHold,issueTick]);
  const refreshWorkspaces=async()=>{try{const d=await get('/api/workspaces');setWorkspaces(d.workspaces);setServer(true);setError('');}catch(e){setServer(false);setError((e as Error).message);}};
  const refreshActivity=async()=>{const version=++activityVersion.current;try{const d=await get('/api/activity');if(version===activityVersion.current){const sessions:ActiveSessionSummary[]=Array.isArray(d.sessions)?d.sessions:[];const fresh=freshCompletions(seenCompletions.current,sessions);seenCompletions.current=new Set([...(seenCompletions.current??[]),...notifiedCompletionIds(sessions)]);setActivity(sessions);if(notificationsEnabled.current&&document.visibilityState==='hidden'&&typeof Notification!=='undefined'&&Notification.permission==='granted')for(const item of fresh){const title=item.completion?.status==='completed'?'Pi work completed':'Pi work ended';const scopeLabel=item.completion?.scope==='kit'?'kit run':'conversation';const body=`${item.workspaceName} · ${item.sessionName} · ${scopeLabel} ${item.completion?.status}`;void (async()=>{try{if(navigator.serviceWorker?.controller){const registration=await navigator.serviceWorker.ready;await registration.showNotification(title,{body,tag:`pi-console-${item.completion?.id}`})}else new Notification(title,{body,tag:`pi-console-${item.completion?.id}`})}catch{/* Browser notifications are best effort. */}})()}}}catch{if(version===activityVersion.current)setActivity([])}};
  // Session lists are workspace-scoped: a delayed reply for workspace A must never land
  // while the user is looking at workspace B.
  const refreshSessions=async(id=workspace)=>{if(!id)return;const gen=navGen();try{const d=await get(`/api/sessions?workspaceId=${encodeURIComponent(id)}`);if(navGen()===gen&&decisionScope.current.split(':')[0]===id)setSessions(d.sessions);}catch(e){if(navGen()===gen)setError((e as Error).message);}};
  useEffect(()=>{void refreshWorkspaces();get('/api/quick-prompts').then(d=>setQuickPrompts(d.prompts)).catch(()=>{});
    const offline=()=>setOnline(false),ready=()=>setOnline(true);window.addEventListener('offline',offline);window.addEventListener('online',ready);
    return()=>{window.removeEventListener('offline',offline);window.removeEventListener('online',ready)};
  },[]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();navigate(workspace?'sessions':'workspaces');if(workspace)requestAnimationFrame(()=>searchRef.current?.focus());}};
    window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);
  },[workspace]);
  useEffect(()=>{if(!workspace)return;void refreshSessions(workspace);const interval=setInterval(()=>void refreshSessions(workspace),10000);return()=>clearInterval(interval)},[workspace]);
  useEffect(()=>{void refreshActivity();const interval=setInterval(()=>void refreshActivity(),5000);return()=>clearInterval(interval)},[]);
  useEffect(()=>{setModelProvider('');setModelSearch('');setModelFilterOpen(false);setCompactControlsOpen(false);if(!workspace||!session){setOptions(undefined);return;}let cancelled=false;setOptions(undefined);
    get(`/api/session/options?workspaceId=${encodeURIComponent(workspace)}&sessionId=${encodeURIComponent(session)}`).then(d=>{if(!cancelled)setOptions(d)}).catch(e=>{if(!cancelled)setError((e as Error).message)});
    return()=>{cancelled=true};
  },[workspace,session]);
  useEffect(()=>{
    if(!workspace||!session)return;
    let cancelled=false;let stream:EventSource|undefined;let timer:ReturnType<typeof setTimeout>|undefined;
    let refreshSeq=0;
    const gen=navGen();
    setSse('connecting');
    // refresh() runs inside the live connection's nav generation: a snapshot from a
    // different server generation is only adopted here (fresh baseline), and each call
    // gets its own request token so a slower earlier response can never roll a newer
    // snapshot back.
    const refresh=async()=>{const request=++refreshSeq;const data:Snapshot=await get(`/api/state?workspaceId=${encodeURIComponent(workspace)}&sessionId=${encodeURIComponent(session)}`);if(cancelled||navGen()!==gen||request!==refreshSeq||!acceptSnapshot(ref.current,data,true))return;ref.current=data;setSnapshot(data);setExecutionEvents(data.events);setServer(true);};
    const reconnect=async()=>{if(cancelled)return;
      try{await get('/api/workspaces');setServer(true);}catch(e){setServer(false);setError((e as Error).message);timer=setTimeout(()=>void reconnect(),2500);return;}
      try{try{await refresh();}catch{const resumed=await post('/api/resume',{workspaceId:workspace,sessionId:session});if(cancelled||navGen()!==gen)return;ref.current=resumed.snapshot;setSnapshot(resumed.snapshot);setExecutionEvents(resumed.snapshot.events);}
        setError('');if(ref.current)connect(ref.current.seq,ref.current.generation);
      }catch(e){if(cancelled)return;setError((e as Error).message);setSse('offline');timer=setTimeout(()=>void reconnect(),2500)}
    };
    const connect=(cursor:number,generation:string)=>{
      if(cancelled)return;
      const previous=stream;stream=undefined;previous?.close();
      const mine=new EventSource(`/api/events?workspaceId=${encodeURIComponent(workspace)}&sessionId=${encodeURIComponent(session)}&since=${cursor}&generation=${encodeURIComponent(generation)}`);stream=mine;
      const live=()=>stream===mine; // ignore callbacks from a stream we already replaced
      mine.onopen=()=>{if(live()){setSse('connected');setServer(true)}};
      mine.onerror=()=>{if(live()){mine.close();if(cancelled)return;setSse('reconnecting');timer=setTimeout(()=>void reconnect(),1200)}};
      mine.addEventListener('execution',e=>{
        if(!live())return;
        const event:ExecutionEvent=JSON.parse((e as MessageEvent).data),before=ref.current;
        // Reject late events from an older connection or a different session even when
        // generation/seq happen to overlap: identity must match the open channel too.
        if(!before||cancelled||event.generation!==before.generation||event.workspaceId!==workspace||event.sessionId!==session||event.seq<=before.seq)return;if(event.seq!==before.seq+1){void refresh().catch(()=>{setSse('reconnecting');stream?.close();timer=setTimeout(()=>void reconnect(),1200)});return;}
        let chat=before.chat;
        if(event.type==='MessageStarted')chat=[...chat,{id:event.entityId,role:'assistant',text:'',complete:false}];
        if(event.type==='MessageDelta')chat=chat.map(m=>m.id===event.entityId?event.payload.channel==='thinking'?{...m,thinking:(m.thinking??'')+String(event.payload.delta??'')}:{...m,text:m.text+String(event.payload.delta??'')}:m);
        if(event.type==='MessageCompleted')chat=event.payload.role==='user'?[...chat,{id:event.entityId,role:'user' as const,text:String(event.payload.text??''),complete:true,...(Array.isArray(event.payload.attachments)?{attachments:event.payload.attachments as Snapshot['chat'][number]['attachments']}:{})}]:chat.some(m=>m.id===event.entityId)?chat.map(m=>m.id===event.entityId?{...m,text:String(event.payload.text??''),thinking:typeof event.payload.thinking==='string'?event.payload.thinking:undefined,tools:Array.isArray(event.payload.tools)?event.payload.tools as typeof m.tools:undefined,complete:true}:m):[...chat,{id:event.entityId,role:'assistant' as const,text:String(event.payload.text??''),thinking:typeof event.payload.thinking==='string'?event.payload.thinking:undefined,tools:Array.isArray(event.payload.tools)?event.payload.tools as Snapshot['chat'][number]['tools']:undefined,complete:true}];
        if (typeof event.payload.chatMessageId==='string' && event.payload.chatTool && ['ToolStarted','ToolProgress','ToolCompleted','ToolFailed'].includes(event.type)) chat=chat.map(message=>message.id===event.payload.chatMessageId?{...message,tools:message.tools?.map(tool=>tool.id===event.toolCallId?event.payload.chatTool as NonNullable<typeof message.tools>[number]:tool)}:message);
        // The authoritative queue projection arrives whole; just replace it.
        const queue=event.type==='QueueChanged'&&Array.isArray(event.payload.queue)?event.payload.queue as QueuedItem[]:before.queue;
        const queueHeld=event.type==='QueueChanged'?event.payload.queueHeld===true:before.queueHeld;
        if(event.type==='RunCompleted'||event.type==='RunFailed')void get(`/api/session/options?workspaceId=${encodeURIComponent(workspace)}&sessionId=${encodeURIComponent(session)}`).then(d=>{if(!cancelled&&navGen()===gen)setOptions(d)}).catch(()=>{});
        if(['RunStarted','RunCompleted','RunFailed','DecisionRequired','DecisionResolved','AgentStarted','AgentCompleted','AgentFailed'].includes(event.type)||(event.type==='ExecutionNodeUpdated'&&event.source==='pi-subagents'))void refreshActivity();
        const next:Snapshot={...before,runtime:event.type==='RunFailed'&&event.status==='interrupted'?'failed':before.runtime,
          seq:event.seq,events:[...before.events,event].slice(-5000),chat,queue,queueHeld,
          activeRunId:event.type==='RunStarted'?event.runId:event.type==='RunCompleted'||event.type==='RunFailed'?undefined:before.activeRunId};
        ref.current=next;setSnapshot(next);if(event.type!=='MessageDelta')setExecutionEvents(next.events);
        if(['RunStarted','RunCompleted','RunFailed','ToolStarted','ToolProgress','ToolCompleted','ToolFailed','ExecutionNodeUpdated','AgentStarted','AgentProgress','AgentCompleted','AgentFailed','DecisionRequired','DecisionResolved'].includes(event.type)){
          if(refreshTimer.current)clearTimeout(refreshTimer.current);refreshTimer.current=setTimeout(()=>void refresh().catch(()=>{setSse('reconnecting');stream?.close();timer=setTimeout(()=>void reconnect(),1200)}),120);
        }
      });
    };
    post('/api/resume',{workspaceId:workspace,sessionId:session}).then(({snapshot:first}:{snapshot:Snapshot})=>{
      if(cancelled||navGen()!==gen)return;ref.current=first;setSnapshot(first);setExecutionEvents(first.events);setServer(true);setError('');connect(first.seq,first.generation);
    }).catch(e=>{if(!cancelled){setError((e as Error).message);setSse('offline')}});
    return()=>{cancelled=true;stream?.close();if(timer)clearTimeout(timer);if(refreshTimer.current)clearTimeout(refreshTimer.current);setSse('offline')};
  },[workspace,session,connectionEpoch]);
  useEffect(()=>{setKitRequest('');setKitStatus({available:false});if(!workspace||!session)return;let cancelled=false;
    let wasRunning=false;
    const refresh=()=>get(`/api/orchestrator?workspaceId=${encodeURIComponent(workspace)}&sessionId=${encodeURIComponent(session)}`).then(d=>{if(!cancelled){setKitStatus(d);if(wasRunning&&!d.job?.running){void refreshSessions(workspace);void refreshActivity()}wasRunning=!!d.job?.running}}).catch(()=>{if(!cancelled)setKitStatus({available:false})});
    void refresh();const timer=setInterval(()=>void refresh(),2000);return()=>{cancelled=true;clearInterval(timer)};
  },[workspace,session]);
  useEffect(()=>{setKitDecisions(undefined);if(!workspace||!session||!kitStatus.available)return;let cancelled=false;const scope=`${workspace}:${session}`;
    const refresh=()=>get(`/api/orchestrator/decisions?workspaceId=${encodeURIComponent(workspace)}&sessionId=${encodeURIComponent(session)}`).then(data=>{if(!cancelled)setKitDecisions({scope,data})}).catch(()=>{if(!cancelled)setKitDecisions(undefined)});
    void refresh();const timer=setInterval(()=>void refresh(),2000);return()=>{cancelled=true;clearInterval(timer)};
  },[workspace,session,kitStatus.available]);
  useEffect(()=>{const box=chatRef.current;if(!box)return;if(followRef.current){requestAnimationFrame(()=>box.scrollTo({top:box.scrollHeight,behavior:'instant'}));setNewContent(false);}else setNewContent(true)},[snapshot?.chat.at(-1)?.text,snapshot?.chat.at(-1)?.thinking,snapshot?.chat.length,kitStatus.job?.progress?.at(-1),kitStatus.job?.report,kitStatus.job?.error]);
  useEffect(()=>{
    if(mobileView!=='chat')return;
    const latest=()=>{if(document.visibilityState==='hidden'||!followRef.current)return;setNewContent(false);requestAnimationFrame(()=>requestAnimationFrame(()=>{const box=chatRef.current;if(box&&followRef.current)box.scrollTop=box.scrollHeight}))};
    latest();document.addEventListener('visibilitychange',latest);window.addEventListener('focus',latest);window.addEventListener('pageshow',latest);
    return()=>{document.removeEventListener('visibilitychange',latest);window.removeEventListener('focus',latest);window.removeEventListener('pageshow',latest)};
  },[mobileView,workspace,session]);
  async function switchWorkspace(id:string,created?:Workspace){const item=created??workspaces.find(w=>w.id===id);if(!item)return;const request=++workspaceSelection.current;let gen=navGen();try{await post('/api/workspaces/update',{id,open:true});if(request!==workspaceSelection.current||navGen()!==gen)return;bumpNav();setWorkspace(id);setSession('');setSessions([]);setSessionQuery('');ref.current=undefined;setSnapshot(undefined);setExecutionEvents([]);setOptions(undefined);navigate('sessions',id,'');gen=navGen();setWorkspaceTools(false);await refreshWorkspaces();if(request===workspaceSelection.current&&navGen()===gen)setError('');}catch(e){if(request===workspaceSelection.current&&navGen()===gen)setError((e as Error).message)}}
  async function renameWorkspace(name:string){const id=workspace,gen=navGen();if(!id||workspaceBusy)return;setWorkspaceBusy('rename');try{const d=await post('/api/workspaces/update',{id,name});if(navGen()===gen&&decisionScope.current.split(':')[0]===id)setWorkspaceName(d.workspace.name);await refreshWorkspaces();if(navGen()===gen)setError('')}catch(e){if(navGen()===gen)setError((e as Error).message)}finally{if(navGen()===gen)if(workspace===id)setWorkspaceBusy('')}}
  async function togglePin(){const id=workspace,gen=navGen(),item=workspaces.find(w=>w.id===id);if(!id||!item||workspaceBusy)return;setWorkspaceBusy('pin');try{await post('/api/workspaces/update',{id,pinned:!item.pinned});if(navGen()===gen){await refreshWorkspaces();setError('')}}catch(e){if(navGen()===gen)setError((e as Error).message)}finally{if(navGen()===gen&&workspace===id)setWorkspaceBusy('')}}
  async function openExplorer(){if(!workspace||explorerBusy)return;const id=workspace;setExplorerBusy(true);setExplorerNotice(undefined);try{await post('/api/workspaces/explorer',{id});setExplorerNotice({id,text:'Opened on the host Windows desktop.',error:false})}catch(e){setExplorerNotice({id,text:(e as Error).message,error:true})}finally{setExplorerBusy(false)}}
  async function removeWorkspace(item:Workspace){if(workspaceBusy)return;if(!window.confirm(`Remove “${item.name}” from Pi Console? Only the registration is removed — the folder and its Pi sessions stay on disk.`))return;const gen=navGen();setWorkspaceBusy('remove');try{await post('/api/workspaces/remove',{id:item.id});if(decisionScope.current.split(':')[0]===item.id){bumpNav();setWorkspace('');setSession('');setSessions([]);ref.current=undefined;setSnapshot(undefined);setExecutionEvents([]);setOptions(undefined);setWorkspaceTools(false);navigate('workspaces','','')}await refreshWorkspaces();void refreshActivity();if(navGen()===gen)setError('')}catch(e){if(navGen()===gen)setError((e as Error).message)}finally{if(navGen()===gen)setWorkspaceBusy('')}}
  const toggleWorkspaceAdd=(trigger:HTMLButtonElement)=>{workspaceAddInvokerRef.current=trigger;setAddWorkspaceOpen(open=>!open);if(!addWorkspaceOpen)requestAnimationFrame(()=>{workspaceCreateRef.current?.scrollIntoView({block:'start'});workspaceCreateRef.current?.focus({preventScroll:true})})};
  const cancelWorkspaceAdd=()=>{setAddWorkspaceOpen(false);requestAnimationFrame(()=>workspaceAddInvokerRef.current?.focus())};
  async function addWorkspace(){if(workspaceBusy)return;const gen=navGen();setWorkspaceBusy('add');try{const d=await post('/api/workspaces',{path});await refreshWorkspaces();await switchWorkspace(d.workspace.id,d.workspace);if(navGen()===gen)setPath('')}catch(e){if(navGen()===gen)setError((e as Error).message)}finally{if(navGen()===gen)setWorkspaceBusy('')}}
  async function newSession(){if(creatingSessionRef.current)return;const ws=workspace,gen=navGen();creatingSessionRef.current=true;setCreatingSession(true);try{const d=await post('/api/sessions',{workspaceId:ws});if(navGen()!==gen||decisionScope.current.split(':')[0]!==ws)return;setSessions(current=>[d.session,...current]);ref.current=undefined;setSnapshot(undefined);setExecutionEvents([]);setOptions(undefined);navigate(preferences.defaultSessionView,ws,d.session.id,'sessions');setError('')}catch(e){if(navGen()===gen)setError((e as Error).message)}finally{creatingSessionRef.current=false;if(navGen()===gen)setCreatingSession(false)}}
  async function changeModel(provider:string,modelId:string){if(!session||optionsBusy)return;const gen=navGen();setOptionsBusy(true);try{const next=await post('/api/session/model',{workspaceId:workspace,sessionId:session,provider,modelId});if(navGen()===gen){setOptions(next);setError('')}}catch(e){if(navGen()===gen)setError((e as Error).message)}finally{if(navGen()===gen)setOptionsBusy(false)}}
  async function changeThinking(level:string){if(!session||optionsBusy)return;const gen=navGen();setOptionsBusy(true);try{const next=await post('/api/session/thinking',{workspaceId:workspace,sessionId:session,level});if(navGen()===gen){setOptions(next);setError('')}}catch(e){if(navGen()===gen)setError((e as Error).message)}finally{if(navGen()===gen)setOptionsBusy(false)}}
  const attachmentType=(file:File)=>{
    if(['image/png','image/jpeg','image/gif','image/webp'].includes(file.type))return {kind:'image',mimeType:file.type} as const;
    const imageExt=file.name.toLowerCase().match(/\.(png|jpe?g|gif|webp)$/)?.[1];
    if(imageExt)return {kind:'image',mimeType:`image/${imageExt==='jpg'?'jpeg':imageExt}` as string} as const;
    if(file.type.startsWith('text/')||['application/json','application/xml','application/javascript'].includes(file.type))return {kind:'text',mimeType:file.type} as const;
    if(/\.(txt|md|json|ts|tsx|js|jsx|css|html?|xml|ya?ml|py|go|rs|ps1|sh|log|csv|svg|c|h|cpp|hpp|java|rb|swift|kt|toml|ini|sql|vue|svelte)$/i.test(file.name))return {kind:'text',mimeType:'text/plain'} as const;
    return undefined;
  };
  function addAttachments(files:FileList|null){if(!files)return;const next=[...attachments,...Array.from(files)];attachRef.current!.value='';
    if(next.length>4){setAttachmentError('Up to 4 files can be attached.');return}
    if(next.some(file=>!file.name||file.name.length>120||file.name.includes('/')||file.name.includes('\\')||!attachmentType(file)||!file.size||file.size>(attachmentType(file)?.kind==='image'?5*1024*1024:64*1024)) || next.reduce((total,file)=>total+file.size,0)>8*1024*1024){setAttachmentError('Choose text files up to 64 KiB or PNG/JPEG/GIF/WebP images up to 5 MiB (8 MiB total).');return}
    setAttachmentError('');setAttachments(next);
  }
  async function serializeAttachments(files:File[]=attachments):Promise<PromptAttachment[]>{return Promise.all(files.map(async file=>{
    const type=attachmentType(file)!;
    if(type.kind==='text')return {kind:'text',name:file.name,mimeType:type.mimeType,text:decodeUtf8(await file.arrayBuffer())};
    const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]??'');reader.onerror=()=>reject(Error('Could not read attached image'));reader.readAsDataURL(file)});
    return {kind:'image',name:file.name,mimeType:type.mimeType,data};
  }));}
  async function send(){if(!session||!snapshot||!draftLoaded||conflictedDraftScopes.current.has(draftScope)||(!pendingSubmission&&!prompt.trim()&&!attachments.length)||(kitBlocked&&!pendingSubmission)||sendingScopesRef.current.has(draftScope)||recyclingScopesRef.current.has(draftScope))return;const ws=workspace,sid=session,gen=navGen(),scope=draftScope;
    const submission:PendingSubmission=pendingSubmission??{requestId:crypto.randomUUID(),text:prompt,files:attachments,...(snapshot.activeRunId?{mode:busyMode}:{})};
    const message=submission.text,sentFiles=submission.files;let requestStarted=false;setSending(scope,true);
    // Once the POST is accepted, the submitted input is cleared immediately — before the
    // state refresh — so a failed refresh can never leave the sent prompt ready for a
    // duplicate re-send. Only the exact submitted text/attachment set is cleared: edits
    // made while the POST was in flight are kept. Clearing still requires the same
    // scope: navigating away mid-send must not wipe another session's composer.
    try{if(!pendingSubmission)await updateComposerDraft(scope,draft=>({...draft,submission}));
      const files=await serializeAttachments(sentFiles);requestStarted=true;await post('/api/prompt',{workspaceId:ws,sessionId:sid,requestId:submission.requestId,message,attachments:files,...(submission.mode?{mode:submission.mode}:{})});
      // An ACK belongs to its submitted scope even after navigation. Keep newer
      // edits, but clear the acknowledged input so returning cannot resend it.
      await updateComposerDraft(scope,draft=>({text:draft.text===message?'':draft.text,files:draft.files===sentFiles?[]:draft.files}));
      if(navGen()===gen&&decisionScope.current===`${ws}:${sid}`){setLastSubmitted(message);setAttachmentError('');void refreshSessions(ws);followRef.current=true;void refreshActivity();
        try{const data:Snapshot=await get(`/api/state?workspaceId=${encodeURIComponent(ws)}&sessionId=${encodeURIComponent(sid)}`);if(navGen()!==gen||decisionScope.current!==`${ws}:${sid}`)return;if(acceptSnapshot(ref.current,data)){ref.current=data;setSnapshot(data);setExecutionEvents(data.events);}setError('')}
        catch{if(navGen()===gen)setError('Message sent, but the refreshed state could not be loaded. Reconnect or wait for the live stream.')}}
    }catch(e){
      if(!requestStarted&&!pendingSubmission){
        // No HTTP attempt occurred. Remove only this new prepared marker,
        // keeping text/files and never erasing an earlier uncertain submission.
        if(composerDraftsRef.current[scope]?.submission?.requestId===submission.requestId)await updateComposerDraft(scope,({submission,...draft})=>draft).catch(()=>{});
        if(navGen()===gen)setError(`Message was not sent: ${(e as Error).message}. Resolve draft storage or attachment errors before sending.`);
      }else if(navGen()===gen)setError((e as Error).message);
    }finally{setSending(scope,false)}}
  const dismissPendingSubmission=()=>{if(window.confirm('Delivery may already have reached Pi. Review the session history first. Stop checking this submission and keep the current input? Sending it again would create a new request and may execute it twice.'))void updateComposerDraft(draftScope,({submission,...draft})=>draft).catch(()=>{})};
  async function answerKit(runId:string,decisionId:string,answer:string){const scope=decisionScope.current;await post('/api/orchestrator/answer',{workspaceId:workspace,sessionId:session,runId,decisionId,answer});
    const data=await get(`/api/orchestrator/decisions?workspaceId=${encodeURIComponent(workspace)}&sessionId=${encodeURIComponent(session)}`);
    if(decisionScope.current===scope)setKitDecisions({scope,data});void refreshActivity();void refreshSessions(workspace);
  }
  async function retryKit(runId:string){const scope=decisionScope.current,gen=navGen();await post('/api/orchestrator/resume',{workspaceId:workspace,sessionId:session,runId});
    if(decisionScope.current===scope&&navGen()===gen)setKitDecisions({scope,data:{runId,decisions:[],canResume:false}});
    void refreshActivity();void refreshSessions(workspace);
  }
  async function retryKitReport(runId:string){const scope=decisionScope.current;await post('/api/orchestrator/report/retry',{workspaceId:workspace,sessionId:session,runId});
    const status=await get(`/api/orchestrator?workspaceId=${encodeURIComponent(workspace)}&sessionId=${encodeURIComponent(session)}`);
    if(decisionScope.current===scope)setKitStatus(status);
  }
  async function markKitReportHandled(runId:string){const scope=decisionScope.current;await post('/api/orchestrator/report/handled',{workspaceId:workspace,sessionId:session,runId,confirmed:true});
    const status=await get(`/api/orchestrator?workspaceId=${encodeURIComponent(workspace)}&sessionId=${encodeURIComponent(session)}`);
    if(decisionScope.current===scope)setKitStatus(status);
  }
  async function startKit(){if(!session||!snapshot||!kitStatus.available||!kitRequest.trim()||snapshot?.activeRunId||kitBlocked||sendingScopesRef.current.has(draftScope)||recyclingScopesRef.current.has(draftScope))return;const ws=workspace,sid=session,gen=navGen(),scope=draftScope;setSending(scope,true);
    try{const d=await post('/api/orchestrator/start',{workspaceId:ws,sessionId:sid,request:kitRequest});if(navGen()!==gen||decisionScope.current!==`${ws}:${sid}`)return;setKitStatus({available:true,job:d.job});void refreshSessions(ws);setKitRequest('');setError('')}catch(e){if(navGen()===gen)setError((e as Error).message)}finally{setSending(scope,false)}}
  async function stop(){if(!snapshot?.activeRunId)return;try{await post('/api/stop',{workspaceId:workspace,sessionId:session});setError('')}catch(e){setError((e as Error).message)}}
  async function saveQueueEdit(item:QueuedItem){
    const draft=queueDrafts[item.id];if(!draft||queueBusy)return;
    const scope=decisionScope.current;setQueueBusy(scope,true);
    try{
      const {item:saved}=await post('/api/queue/edit',{workspaceId:workspace,sessionId:session,id:item.id,revision:draft.revision,text:draft.text});
      // Reconcile only the submitted item's draft, even if its screen is hidden.
      // Newer typing survives, with the revision acknowledged by this save.
      setQueueDrafts(old=>{
        const latest=old[item.id];if(!latest||latest.revision!==draft.revision)return old;
        const next={...old};
        if(latest.text===draft.text)delete next[item.id];
        else next[item.id]={...latest,revision:saved.revision};
        return next;
      });
      if(decisionScope.current===scope){
        const before=ref.current;
        // The HTTP acknowledgement can beat SSE. Do not let an immediate re-edit
        // seed an old revision, or overwrite a newer/claimed/removed queue item.
        if(saved&&before?.session.id===session&&before.session.workspaceId===workspace){
          const next={...before,queue:before.queue?.map(queued=>queued.id===saved.id&&queued.status==='pending'&&queued.revision===draft.revision?saved:queued)};
          ref.current=next;setSnapshot(next);
        }
        setError('');
      }
    }catch(e){if(decisionScope.current===scope)setError((e as Error).message)}finally{setQueueBusy(scope,false)}
  }
  async function removeQueued(item:QueuedItem){if(queueBusy)return;const scope=decisionScope.current;setQueueBusy(scope,true);try{await post('/api/queue/remove',{workspaceId:workspace,sessionId:session,id:item.id});if(decisionScope.current===scope){setQueueDrafts(old=>{const next={...old};delete next[item.id];return next});setError('')}}catch(e){if(decisionScope.current===scope)setError((e as Error).message)}finally{setQueueBusy(scope,false)}}
  async function resumeQueue(){if(queueBusy||recyclingScopesRef.current.has(draftScope))return;
    // Items whose send was already attempted (dispatching at restart, refused/failed
    // dispatch, interrupted worker) may have reached Pi — warn before resending.
    // Items merely restored-as-pending never left the console and resume safely.
    const uncertain=!!snapshot?.queue?.some(item=>item.status==='held'&&!(item.error??'').startsWith('restored after restart'));
    if(uncertain&&!window.confirm('A held queued prompt may already have been delivered to Pi — its delivery was not confirmed. Resuming could send it twice. Continue?'))return;
    const scope=decisionScope.current;setQueueBusy(scope,true);try{await post('/api/queue/resume',{workspaceId:workspace,sessionId:session});if(decisionScope.current===scope)setError('')}catch(e){if(decisionScope.current===scope)setError((e as Error).message)}finally{setQueueBusy(scope,false)}}
  async function recycleSession(item:SessionInfo){
    const ws=workspace,scope=`${ws}:${item.id}`,key=JSON.stringify([ws,item.id]),fromScope=decisionScope.current;
    if(!ws||recycleDisabled(item)||!window.confirm(`Move “${item.name??'New conversation'}” to this server’s Windows Recycle Bin? This Pi session may also be used by other apps.`))return;
    recyclingScopesRef.current.add(key);setRecyclingScopes(old=>({...old,[key]:true}));setRecycleErrors(old=>{const next={...old};delete next[key];return next});
    try{await post('/api/session/recycle',{workspaceId:ws,sessionId:item.id});
      if(decisionScope.current.split(':')[0]===ws){
        setSessions(current=>current.filter(s=>s.id!==item.id));
        if(decisionScope.current===fromScope)setError('');
        if(decisionScope.current===scope){bumpNav();ref.current=undefined;setSnapshot(undefined);setExecutionEvents([]);setOptions(undefined);navigate(history.state?.view==='workspaces'?'workspaces':'sessions',ws,'')}
      }
      void refreshActivity();
    }catch(e){setRecycleErrors(old=>({...old,[key]:(e as Error).message}));if(decisionScope.current===fromScope)setError((e as Error).message)}
    finally{recyclingScopesRef.current.delete(key);setRecyclingScopes(old=>{const next={...old};delete next[key];return next})}
  }
  async function openFile(path:string,line?:number,fromPreview=false){if(!workspace)return;if(!fromPreview){const element=document.activeElement instanceof HTMLElement?document.activeElement:undefined;const message=element?.closest<HTMLElement>('[data-message-id]');fileInvoker.current={element,messageId:message?.dataset.messageId,linkIndex:Array.from(message?.querySelectorAll('.file-link')??[]).indexOf(element!)}}const request=++fileRequest.current;setFileCopyStatus('');if(fromPreview){if(filePreview?.path===path&&filePreview.line===line)return;if(filePreview)setFileHistory(old=>[...old,filePreview])}else setFileHistory([]);setFilePreview({path,line});try{const media=/\.(png|jpe?g|gif|webp|mp4|webm)$/i.test(path);const file=await get(`/api/workspace/${media?'media/info':'text'}?workspaceId=${encodeURIComponent(workspace)}&path=${encodeURIComponent(path)}`);if(request===fileRequest.current)setFilePreview(media?{path:file.path,format:file.format,mediaUrl:`/api/workspace/media?workspaceId=${encodeURIComponent(workspace)}&path=${encodeURIComponent(file.path)}`}:{path:file.path,line,content:file.content,format:file.format})}catch(e){if(request===fileRequest.current)setFilePreview({path,line,error:(e as Error).message})}}
  function backFile(){if(!fileHistory.length)return;fileRequest.current++;setFileCopyStatus('');setFilePreview(fileHistory.at(-1));setFileHistory(old=>old.slice(0,-1))}
  async function copyFile(){if(filePreview?.content===undefined)return;const request=fileRequest.current;try{await navigator.clipboard.writeText(filePreview.content);if(request===fileRequest.current)setFileCopyStatus('Copied')}catch{if(request===fileRequest.current)setFileCopyStatus('Copy failed — check clipboard permission')}}
  function reopen(){setError('');setConnectionEpoch(v=>v+1)}
  async function savePrompts(){const values=quickDraft.split('\n').map(s=>s.trim()).filter(Boolean);if(!validQuickPrompts(values)){setError('Up to 8 prompts, 200 characters each');return}try{const d=await post('/api/quick-prompts',{prompts:values});setQuickPrompts(d.prompts);setEditPrompts(false);setError('')}catch(e){setError((e as Error).message)}}
  // Opening the existing list is view-only: an in-flight send and the current
  // snapshot stay bound to their session until a different row is selected.
  const openSessionList=()=>{setSessionQuery('');navigate('sessions');requestAnimationFrame(()=>searchRef.current?.focus())};
  const chooseSession=(id:string)=>{if(id!==session){ref.current=undefined;setSnapshot(undefined);setExecutionEvents([]);setOptions(undefined)}setPromptHistoryOpen(false);navigate(preferences.defaultSessionView,workspace,id,'sessions');followRef.current=true};
  const openActive=(item:ActiveSessionSummary)=>{if(item.workspaceId!==workspace){setSessions([]);void refreshSessions(item.workspaceId)}if(item.workspaceId!==workspace||item.sessionId!==session){ref.current=undefined;setSnapshot(undefined);setExecutionEvents([]);setOptions(undefined)}setPromptHistoryOpen(false);navigate('chat',item.workspaceId,item.sessionId,mobileView==='sessions'?'sessions':'workspaces');followRef.current=true};
  const jumpToPrompt=(id:string)=>{setPromptHistoryOpen(false);const box=chatRef.current;const node=Array.from(box?.querySelectorAll<HTMLElement>('[data-message-id]')??[]).find(el=>el.dataset.messageId===id);if(!box||!node)return;followRef.current=false;box.scrollTo({top:node.getBoundingClientRect().top-box.getBoundingClientRect().top+box.scrollTop-12,behavior:'smooth'});requestAnimationFrame(()=>node.focus({preventScroll:true}))};
  const usePrompt=(value:string)=>{setPrompt(prev=>prev?`${prev.trimEnd()}\n${value}`:value);composerRef.current?.focus()};
  const insertVoice=(text:string)=>{const field=composerRef.current;const start=field?.selectionStart??prompt.length;const scope=decisionScope.current;setPrompt(value=>value.slice(0,start)+text+value.slice(start));requestAnimationFrame(()=>{if(decisionScope.current!==scope)return;field?.focus();field?.setSelectionRange(start+text.length,start+text.length)})};
  const onComposerKey=(e:React.KeyboardEvent<HTMLTextAreaElement>)=>{if(e.nativeEvent.isComposing)return;if(e.key==='Enter'&&((e.ctrlKey||e.metaKey)||(!e.shiftKey&&!coarsePointer))){e.preventDefault();void send()}if(e.key==='Escape'&&snapshot?.activeRunId&&!kitBlocked){e.preventDefault();void stop()}};
  const sessionControls=<div id="session-controls" className="session-controls"><div className="model-control"><div className="model-heading"><span>Model</span><button type="button" aria-label="Find models" aria-expanded={modelFilterOpen} disabled={!session||!options} onClick={()=>{setModelFilterOpen(open=>!open);requestAnimationFrame(()=>modelSearchRef.current?.focus())}}>Find models</button></div><select aria-label="Model" value={selectedModel?modelKey(selectedModel):''} disabled={!session||!options||optionsBusy||sending||!!snapshot?.activeRunId} onChange={e=>{const choice=options?.models.find(m=>modelKey(m)===e.target.value);if(choice){setModelProvider(choice.provider);setModelSearch('');setModelFilterOpen(false);void changeModel(choice.provider,choice.id)}}}><option value="">{options?.models.length?'Select a model':'No models available'}</option>{visibleModels.map(m=><option key={modelKey(m)} value={modelKey(m)}>{m.provider} / {m.name}</option>)}</select>{modelFilterOpen&&<div className="model-filter" role="group" aria-label="Find models"><label>Provider<select aria-label="Model provider" value={providerFilter} onChange={e=>setModelProvider(e.target.value)}><option value="*">All providers</option>{providers.map(provider=><option key={provider} value={provider}>{provider}</option>)}</select></label><label>Search models<input ref={modelSearchRef} aria-label="Search models" value={modelSearch} onChange={e=>setModelSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setModelFilterOpen(false)}} placeholder="Name or model ID"/></label><small>{matchingModels.length>80?`Showing first 80 of ${matchingModels.length}; narrow your search`:`${matchingModels.length} matching models`}</small><button type="button" onClick={()=>setModelFilterOpen(false)}>Done</button></div>}</div><label>Thinking<select aria-label="Thinking" value={options?.thinkingLevel??''} disabled={!session||!options||optionsBusy||sending||!!snapshot?.activeRunId} onChange={e=>void changeThinking(e.target.value)}><option value="">—</option>{options?.thinkingLevels.map(level=><option key={level} value={level}>{level}</option>)}</select></label><div className="context-usage" aria-label="Context usage"><span>Context <b>{typeof options?.contextUsage?.percent==='number'?`${Math.round(options.contextUsage.percent)}%`:'—'}</b></span>{typeof options?.contextUsage?.percent==='number'?<><progress aria-label="Context usage percentage" value={Math.max(0,Math.min(100,options.contextUsage.percent))} max="100"/><small>{options.contextUsage.tokens?.toLocaleString()??'—'} / {options.contextUsage.contextWindow.toLocaleString()} tokens</small></>:<small>Measured after a response</small>}</div></div>;
  const recycleDisabled=(item:SessionInfo)=>!!item.running||!!item.decisionCount||sendingScopesRef.current.has(JSON.stringify([workspace,item.id]))||recyclingScopesRef.current.has(JSON.stringify([workspace,item.id]))||(item.id===session&&!!currentSnapshot&&(!!currentSnapshot.activeRunId||!!currentSnapshot.execution.decisionCount||kitBlocked));
  const workspaceMenu=current&&compactScreen?<WorkspaceMenu key={`${workspace}:${mobileView}`} name={current.name} disabled={current.valid===false||explorerBusy} onOpenHost={()=>void openExplorer()} onEdit={()=>{setWorkspaceTools(true);navigate('workspaces');requestAnimationFrame(()=>document.querySelector<HTMLInputElement>('.workspace-rename-label input')?.focus())}}/>:null;
  const usage=options?.contextUsage;
  const compactTokens=(value:number|null)=>value===null?'—':value>=1000000?`${Math.round(value/100000)/10}M`:value>=1000?`${Math.round(value/100)/10}k`:String(value);
  const contextText=typeof usage?.percent==='number'?`Context ${Math.round(usage.percent)}% · ${compactTokens(usage.tokens)}/${compactTokens(usage.contextWindow)}`:'Context —';
  const contextSummary=<small className="context-summary" aria-label="Current context usage" title={typeof usage?.percent==='number'?`Context: ${usage.tokens?.toLocaleString()??'—'} / ${usage.contextWindow.toLocaleString()} tokens (${Math.round(usage.percent)}%)`:'Measured after a response'}>{contextText}</small>;
  const chatSection=<section className="chat-panel"><div className="chat-heading"><div><h2 title={selected?.name} aria-label={selected?.name??'Your next idea starts here'}><button className="session-picker-trigger" aria-label="Switch session" disabled={!workspace} onClick={openSessionList}>{selected?.name??'Your next idea starts here'}</button></h2>{!shortScreen&&<ConversationStatus key={draftScope} status={currentStatus} snapshot={currentSnapshot} onExecution={()=>navigate('execution')}/>}</div><div className="run-badge"><button className="desktop-execution-toggle" aria-label={executionExpanded?'Hide execution details':'Show execution details'} aria-expanded={executionExpanded} aria-controls="execution-details" data-attention={executionAttention} title={executionAttention?executionAttentionLabel:undefined} onClick={()=>setExecutionExpanded(open=>!open)}>{executionExpanded?'Hide details':'Execution'} {executionAttention&&<span role="status" aria-label={executionAttentionLabel}>⚠</span>} <span aria-hidden="true">{executionExpanded?'›':'‹'}</span></button><button className="prompt-history-trigger" aria-label="Open prompt history" aria-expanded={promptHistoryOpen} disabled={!promptHistory.length} onClick={()=>{setPromptHistoryOpen(v=>!v);setPromptHistoryLimit(80)}}>Instructions · {promptHistory.length}</button></div></div>
    {compactScreen?<><div className="model-summary-bar"><span title={selectedModel?`${selectedModel.provider} / ${selectedModel.id}`:undefined}>{selectedModelName??(options?'No model selected':'Loading model…')}</span>{mobileView==='chat'&&!shortScreen&&contextSummary}<button aria-label="Model settings" aria-haspopup="dialog" aria-expanded={compactControlsOpen} aria-controls="model-settings-dialog" disabled={!session} onClick={()=>setCompactControlsOpen(true)}>⚙ Settings</button></div><ModelSettingsDialog open={compactControlsOpen} onClose={()=>setCompactControlsOpen(false)}>{sessionControls}</ModelSettingsDialog></>:sessionControls}
    {promptHistoryOpen&&<div className="prompt-history" role="region" aria-label="Prompt history"><div className="prompt-history-heading"><strong>Instructions in this session</strong><button aria-label="Close prompt history" onClick={()=>setPromptHistoryOpen(false)}>✕</button></div><div className="prompt-history-list">{promptHistory.slice(-promptHistoryLimit).reverse().map((item,index)=><button key={item.id} onClick={()=>jumpToPrompt(item.id)}><span>#{promptHistory.length-index}</span><span>{item.text.replace(/\s+/g,' ').slice(0,110)}{item.attachments?.length?` · 📎 ${item.attachments.map(a=>a.name).join(', ')}`:''}</span>↗</button>)}{promptHistory.length>promptHistoryLimit&&<button onClick={()=>setPromptHistoryLimit(v=>v+80)}>Show earlier instructions</button>}</div></div>}
    <div className="chat" aria-label="Chat output" ref={chatRef} onScroll={e=>{const el=e.currentTarget;followRef.current=el.scrollHeight-el.scrollTop-el.clientHeight<85;if(followRef.current)setNewContent(false)}}>{snapshot?.chat.length?snapshot.chat.map(m=><ChatItem key={m.id} message={m} onOpenFile={openFile} showProgress={false} waitingLabel={currentSnapshot?.activeRunId?(preferences.language==='ja'?'Piの出力を待っています…':'Waiting for Pi output…'):(preferences.language==='ja'?'出力がないまま実行が終了しました':'No output received · run ended')}/>):!kitStatus.job&&<div className="chat-empty"><span className="empty-glyph" aria-hidden="true">›_</span><h3>{session?'A fresh conversation':'Make space for what’s next'}</h3><p>{session?'Start with a question, a task or a piece of code. Pi will keep the thread here.':'Choose a workspace and start a session to work with Pi.'}</p>{session&&<small>New sessions are temporary until the first prompt is sent.</small>}</div>}{kitStatus.job && <KitChatReport key={`${session}:${kitStatus.job.runId??kitStatus.job.startedAt}`} job={kitStatus.job}/>}</div>
    {newContent&&<button className="jump" onClick={()=>{followRef.current=true;chatRef.current?.scrollTo({top:chatRef.current.scrollHeight,behavior:'smooth'});setNewContent(false)}}>New content · Jump to bottom</button>}
    <div className="composer-dock">
      <details className="quick-details"><summary><span className="quick-caption">{defaultPrompts?'Suggested prompts':'Saved prompts'}</span></summary><div className="quick-row">{displayedPrompts.map((value,index)=><button key={index} title={value} onClick={()=>usePrompt(value)}>{value}</button>)}<button aria-label="Edit saved shortcuts" onClick={()=>{setQuickDraft(displayedPrompts.join('\n'));setEditPrompts(v=>!v)}}>Edit prompts</button></div>
      {editPrompts&&<div className="quick-editor"><label>Quick prompts (one per line, insert only)<textarea aria-label="Quick prompts" value={quickDraft} onChange={e=>setQuickDraft(e.target.value)}/></label><button onClick={()=>void savePrompts()}>Save prompts</button></div>}</details>
      <div className="composer-attachment-bar">
      {!!attachments.length&&<div className="attachment-list" aria-label="Attached files">{attachments.map((file,i)=><span key={`${file.name}-${i}`} className="attachment-chip" title={file.name}>{file.name}<button aria-label={`Remove ${file.name}`} onClick={()=>{setAttachments(old=>old.filter((_,index)=>index!==i));setAttachmentError('')}}>×</button></span>)}</div>}</div>
      {attachmentError&&<span className="attachment-error" role="alert">{attachmentError}</span>}
      {draftWarning&&<span className="attachment-error" role="alert">{draftWarning}</span>}
      {draftConflict&&<div className="attachment-error" role="alert">Draft changed in another tab or was recovered from storage. Your local input is kept here and will not overwrite the saved draft. Copy it before replacing it. <button onClick={reloadSavedDraft}>Load saved draft</button></div>}
      {pendingSubmission&&<div className="attachment-error" role="alert">{sending?'Waiting for acknowledgement.':'Delivery unconfirmed. Review the session history; do not submit a new copy.'} <button disabled={sending||draftConflict||!snapshot||!server} onClick={()=>void send()}>Check delivery · same request</button><button disabled={sending||draftConflict} onClick={dismissPendingSubmission}>Resolve manually</button></div>}
      {!!(currentSnapshot?.queue?.length||currentSnapshot?.queueHeld)&&<QueueDisclosure key={draftScope} compact={compactScreen} count={currentSnapshot?.queue?.length??0} editing={!!currentSnapshot?.queue?.some(item=>!!queueDrafts[item.id])} warning={currentSnapshot?.queueHeld||currentSnapshot?.queue?.some(item=>item.status==='held'||item.status==='failed')?<div className="queue-held-notice" role="status">{currentSnapshot?.queueHeld?(compactScreen?'Queue paused · delivery unconfirmed.':'Queue is paused — an item’s delivery to Pi was not confirmed (stop, error or server restart). Review it, then '):'Queue needs review · failed/unconfirmed delivery.'}{currentSnapshot?.queueHeld&&<><button className="queue-resume" disabled={!!queueBusy||recycling} onClick={()=>void resumeQueue()}>Resume queued</button>{!compactScreen&&' to send it, or Remove to discard.'}</>}</div>:undefined}>{currentSnapshot?.queue?.map(item=><div key={item.id} className={`queue-item${item.status!=='pending'?' is-locked':''}`} data-status={item.status}>
        {queueDrafts[item.id]?<div className="queue-edit"><textarea aria-label={`Edit queued message ${(currentSnapshot?.queue??[]).indexOf(item)+1}`} value={queueDrafts[item.id].text} onChange={e=>setQueueDrafts(old=>({...old,[item.id]:{...old[item.id],text:e.target.value}}))} rows={3}/>{!!item.attachments?.length&&<small className="queue-attachments">Attachments kept: {item.attachments.map(a=>a.name).join(', ')}</small>}<div className="queue-edit-actions"><button disabled={!queueDrafts[item.id].text.trim()||!!queueBusy} onClick={()=>void saveQueueEdit(item)}>Save</button><button disabled={!!queueBusy} onClick={()=>setQueueDrafts(old=>{const next={...old};delete next[item.id];return next})}>Cancel</button></div></div>
        :<><span className="queue-text">{item.message}{!!item.attachments?.length&&<small className="queue-attachments"> 📎 {item.attachments.map(a=>a.name).join(', ')}</small>}</span><span className="queue-item-actions">{item.status==='pending'?<><button aria-label={`Edit queued message ${(currentSnapshot?.queue??[]).indexOf(item)+1}`} disabled={!!queueBusy} onClick={()=>setQueueDrafts(old=>({...old,[item.id]:{text:item.message,revision:item.revision}}))}>Edit</button><button aria-label={`Remove queued message ${(currentSnapshot?.queue??[]).indexOf(item)+1}`} disabled={!!queueBusy} onClick={()=>void removeQueued(item)}>Remove</button></>:item.status==='dispatching'?<small>Sending to Pi — can no longer be edited</small>:item.status==='held'?<><small role="alert">Held — delivery unconfirmed. {item.error}</small><button aria-label={`Remove queued message ${(currentSnapshot?.queue??[]).indexOf(item)+1}`} disabled={!!queueBusy} onClick={()=>void removeQueued(item)}>Remove</button></>:<><small role="alert">Send failed: {item.error}</small><button aria-label={`Remove queued message ${(currentSnapshot?.queue??[]).indexOf(item)+1}`} disabled={!!queueBusy} onClick={()=>void removeQueued(item)}>Remove</button></>}</span></>}
      </div>)}</QueueDisclosure>}
      {kitBlocked&&<div className="kit-chat-notice" role="status">Pi prompts are paused until the kit run finishes. {kitStatus.job?.reporting?'Saving the kit report to Pi cannot be stopped here.':'Stop only applies to Pi runs.'} {kitAwaiting&&<button onClick={()=>navigate('execution')}>{retryAvailable?'Retry in Execution':'Answer in Execution'}</button>}</div>}
      {chatAllowed&&!kitBlocked&&<div className="kit-chat-notice" role="status">Kit run remains paused. You can use Pi chat, or retry the kit in Execution.</div>}
      {session&&!snapshot?.chat.length&&!kitStatus.job&&<small className="first-prompt-note"><span className="full-cost-note">Sending a prompt calls the selected Pi model; provider charges may apply.</span><span className="compact-cost-note">Sending calls the selected Pi model · charges may apply.</span></small>}
      {recycling&&<small role="status">Moving this session to the server's Windows Recycle Bin…</small>}
      <div className="composer-input" onClick={e=>{if(e.target===e.currentTarget)composerRef.current?.focus()}}><label className="composer-label">Prompt<textarea ref={composerRef} aria-label="Prompt" aria-describedby="composer-send-hint" placeholder="Ask Pi about this workspace…" value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={onComposerKey} disabled={!session||!draftLoaded||kitBlocked}/></label>
      <input ref={attachRef} className="attach-input" aria-label="Choose files" type="file" multiple disabled={!session||!draftLoaded||kitBlocked||sending} accept="image/png,image/jpeg,image/gif,image/webp,text/*,.txt,.md,.json,.ts,.tsx,.js,.jsx,.css,.html,.xml,.yaml,.yml,.py,.go,.rs,.ps1,.sh,.log,.csv,.svg,.c,.h,.cpp,.hpp,.java,.rb,.swift,.kt,.toml,.ini,.sql,.vue,.svelte" onChange={e=>addAttachments(e.target.files)}/><button className="attach-button" aria-label="Attach files" title="Attach files · text and images, up to 4" disabled={!session||!draftLoaded||kitBlocked||sending} onClick={()=>attachRef.current?.click()}><span aria-hidden="true">📎</span><span className="attach-label"> Attach</span></button><VoiceInput scope={JSON.stringify([workspace,session,mobileView])} enabled={!!session&&draftLoaded&&!kitBlocked&&!sending} language={preferences.language} onInsert={insertVoice}/><button type="button" className="compact-controls-trigger" aria-haspopup="dialog" aria-expanded={compactControlsOpen} aria-controls="model-settings-dialog" onClick={()=>setCompactControlsOpen(true)}>Model / Thinking</button></div>
      <div className="composer-actions"><span id="composer-send-hint">{kitBlocked?'Pi chat resumes when the kit run finishes':snapshot?.activeRunId?(busyMode==='steer'?'Immediate steering · sent to Pi now, cannot edit':'Adds to queue · sends after Pi finishes, editable'):coarsePointer?'Enter for a line break · tap Send to send':'Enter to send  ·  Shift+Enter for a line break'}</span>{!!snapshot?.activeRunId&&!kitBlocked&&<label className="busy-mode">Delivery<select aria-label="Message delivery" value={busyMode} onChange={e=>setBusyMode(e.target.value as 'followUp'|'steer')}><option value="followUp">Queue after run (editable)</option><option value="steer">Steer now · immediate, cannot edit</option></select></label>}{!!snapshot?.activeRunId&&!kitBlocked&&<button className="button-primary" disabled={!session||!snapshot||!draftLoaded||!!pendingSubmission||draftConflict||(!prompt.trim()&&!attachments.length)||sending||recycling||!server} onClick={()=>void send()}>{busyMode==='steer'?'Steer now':'Queue'} <span aria-hidden="true">↗</span></button>}{snapshot?.activeRunId?<button className="stop" disabled={kitBlocked} title={kitBlocked?'The Orchestrator owns this session; its Pi report cannot be stopped here.':undefined} onClick={()=>void stop()}>{kitBlocked?kitStatus.job?.reporting?'Saving kit report…':'Stop unavailable':'Stop'}</button>:<button className="button-primary" disabled={!session||!snapshot||!draftLoaded||!!pendingSubmission||draftConflict||(!prompt.trim()&&!attachments.length)||kitBlocked||sending||recycling||!server} onClick={()=>void send()}>Send <span aria-hidden="true">↗</span></button>}</div>
    </div>
  </section>;
  return <><main className={`app-shell view-${mobileView}`}><header className="app-header"><div className="brand"><span className="brand-mark" aria-hidden="true">›_</span><div><h1>pi-console</h1><span className="brand-subtitle">Your development space</span></div></div><div className="header-actions">{!!(needsInput||activeCount||completedCount)&&<button className="activity-trigger" aria-label="Active session alerts" onClick={()=>{navigate('workspaces');requestAnimationFrame(()=>{const inbox=document.querySelector<HTMLDetailsElement>('.activity-inbox-details');if(inbox){inbox.open=true;inbox.scrollIntoView({block:'start'})}})}}>{needsInput?`⚠ ${needsInput}`:''}{needsInput&&activeCount?' · ':''}{activeCount?`● ${activeCount}`:''}{completedCount?`${needsInput||activeCount?' · ':''}✓ ${completedCount}`:''}</button>}<button className="settings-trigger" onClick={()=>navigate('settings')} aria-label="Open settings">⚙ <span>{preferences.language==='ja'?'設定':'Settings'}</span></button><span className="connection" role="status" aria-label="connection" data-connected={status==='Runtime healthy'} data-warning={/failed|unavailable|offline|reconnecting/i.test(status)}><span className="connection-dot" aria-hidden="true"/>{status}</span></div></header>
    {failures&&<aside ref={issueToastRef} className="issue-toast" role="alert" aria-label="Recent tool or run issue" onPointerEnter={e=>{if(e.pointerType!=='touch'){issuePointerInside.current=true;syncIssueHold(failures.eventId)}}} onPointerLeave={e=>{if(e.pointerType!=='touch'){issuePointerInside.current=false;syncIssueHold(failures.eventId)}}} onFocusCapture={()=>syncIssueHold(failures.eventId)} onBlurCapture={()=>requestAnimationFrame(()=>syncIssueHold(failures.eventId))}><details onToggle={()=>requestAnimationFrame(()=>syncIssueHold(failures.eventId))}><summary>Recent issue · {String(failures.payload.summary??failures.type)}</summary><p>{failures.type} · {failures.status??'status unknown'}. Retryability was not confirmed; inspect Execution history for context.</p><details onToggle={()=>requestAnimationFrame(()=>syncIssueHold(failures.eventId))}><summary>Technical details</summary><code>{failures.sourceRef?.kind??failures.source} · {failures.entityId}</code></details>{lastSubmitted&&<button onClick={()=>{setPrompt(lastSubmitted);navigate('chat')}}>Restore last prompt</button>}</details><button className="issue-link" onClick={()=>{setFocusedIssue({workspaceId:workspace,sessionId:session,eventId:failures.eventId});dismissIssue(failures.eventId);navigate('execution')}}>View in Execution</button><button className="issue-dismiss" aria-label="Dismiss recent issue" onClick={()=>dismissIssue(failures.eventId)}>×</button></aside>}
    {(error||!server||snapshot?.runtime==='failed')&&<div className="alerts">
      {(error||!server)&&<section className="error-card" role="alert"><b>{server?'Something needs your attention':'Server unavailable'}</b><p>{error||'The server is not responding. Pi state is unknown.'}</p><div className="error-actions"><button onClick={()=>{void refreshWorkspaces();if(session)reopen()}}>Reconnect / retry</button>{!['localhost','127.0.0.1'].includes(location.hostname)&&<button onClick={()=>location.assign('/')}>Reload / Access sign-in</button>}</div></section>}
      {snapshot?.runtime==='failed'&&<section className="error-card"><b>Pi process stopped unexpectedly</b><p>The run was interrupted. Reopen this session to continue safely.</p><button onClick={()=>void reopen()}>Reopen session</button></section>}
    </div>}
    {!!visibleActivity.length&&mobileView!=='settings'&&<section className="activity-inbox" aria-label="Activity notifications"><details className="activity-inbox-details"><summary className="activity-inbox-heading"><strong>{['chat','execution'].includes(mobileView)?'Other sessions':'Activity'}</strong><span>{needsInput} need input · {activeCount} running · {completedCount} finished</span></summary><div className="activity-inbox-list">{visibleActivity.map(item=><div className="activity-card" key={item.sessionId}><button onClick={()=>openActive(item)}><span className="activity-inbox-name"><b>{item.sessionName}</b><small>{item.workspaceName}</small>{item.work.slice(0,4).map(w=><small key={w.id}>{w.kind}: {w.label} · {w.status}{w.action?` · ${w.action}`:''}</small>)}</span><span className="activity-inbox-status">{item.decisionCount>0&&<em>{item.decisionCount} need input</em>}{item.running&&<em className="is-running">Running</em>}{!item.running&&item.work.some(w=>w.status==='blocked')&&<em>Blocked</em>}{!item.running&&!item.decisionCount&&!item.work.some(w=>w.status==='blocked')&&item.work.some(w=>w.status==='waiting')&&<em>Waiting</em>}{item.completion&&!dismissed.includes(item.completion.id)&&<em>{completionLabel(item.completion)} {item.completion.status} · {new Date(item.completion.at).toLocaleTimeString()}</em>}</span></button>{item.completion&&!dismissed.includes(item.completion.id)&&<button className="activity-dismiss" aria-label={`Dismiss ${item.sessionName} completion`} onClick={()=>dismissCompletion(item.completion!.id)}>×</button>}</div>)}</div></details></section>}
    {(mobileView==='chat'||mobileView==='execution')&&<div className="session-toolbar"><button onClick={()=>mobileView==='execution'?navigate('chat'):navigate(sessionReturn,workspace,'')}>{mobileView==='execution'?'← Chat':sessionReturn==='workspaces'?preferences.language==='ja'?'← ワークスペース':'← Workspaces':preferences.language==='ja'?'← セッション':'← Sessions'}</button><div className="session-toolbar-context"><h2 className={mobileView==='chat'?'compact-conversation-title':undefined} title={selected?.name} aria-label={selected?.name??'New conversation'}>{mobileView==='chat'?<button className="session-picker-trigger" aria-label="Switch session" title="Switch session" disabled={!workspace} onClick={openSessionList}>{selected?.name??'New conversation'}</button>:selected?.name??'New conversation'}</h2><div className="workspace-context-line"><span className="workspace-context" title={current?.name}>{current?.name}</span>{compactScreen&&(shortScreen||mobileView==='execution')&&contextSummary}</div></div>{mobileView==='chat'&&shortScreen&&<div className="compact-conversation-status"><ConversationStatus key={draftScope} status={currentStatus} snapshot={currentSnapshot} onExecution={()=>navigate('execution')}/></div>}</div>}
    {mobileView==='settings'?<SettingsPage preferences={preferences} onChange={updatePreferences} onBack={()=>{if(history.state?.fromConsole)history.back();else navigate('workspaces')}} workspaceCount={workspaces.length} sessionCount={sessions.length} connected={server&&online} availableModels={options?.models}/>:<div className="console-layout"><aside className="sidebar"><section className="workspace-hub"><span className="eyebrow">YOUR SPACE</span><div className="section-heading"><h2>Workspaces</h2></div><p>Choose an existing workspace to see its sessions.</p><input aria-label="Find workspace" placeholder="Find workspace…" value={workspaceQuery} onChange={e=>setWorkspaceQuery(e.target.value)}/><div className="workspace-hub-list">{availableWorkspaces.length?availableWorkspaces.map(w=><button key={w.id} className="workspace-card" onClick={()=>void switchWorkspace(w.id)}><span className="workspace-card-icon" aria-hidden="true">{w.pinned?'★':'⌘'}</span><span><b>{w.name}</b><small title={w.path}>{w.path}</small><small>Last opened {new Date(w.lastOpenedAt).toLocaleString()}</small>{activity.filter(a=>a.workspaceId===w.id).map(a=><small className="workspace-activity" key={a.sessionId}>{a.decisionCount>0?`${a.decisionCount} need input · `:''}{a.running?'Running · ':''}{a.sessionName}</small>)}</span><span aria-hidden="true">›</span></button>):<p className="session-empty">{workspaceQuery?'No matching workspaces.':'No workspaces yet. Add one below.'}</p>}</div><button className="workspace-add-shortcut" aria-expanded={addWorkspaceOpen} aria-controls="workspace-add-form" onClick={e=>toggleWorkspaceAdd(e.currentTarget)}>＋ Add a workspace</button>{unavailableWorkspaces.length>0&&<details className="unavailable-workspaces"><summary>Unavailable paths · {unavailableWorkspaces.length}</summary>{unavailableWorkspaces.map(w=><p key={w.id} title={w.path}>{w.name} · {w.path} <button aria-label={`Remove ${w.name} from Pi Console`} onClick={()=>void removeWorkspace(w)}>Remove</button></p>)}</details>}</section><section className={`workspace-bar ${current?'has-workspace':''} ${workspaceTools?'expanded':''} ${addWorkspaceOpen?'adding-workspace':''}`}><div className="section-heading"><span className="eyebrow">WORKSPACE</span>{current&&<span className="workspace-symbol" aria-hidden="true">⌘</span>}</div><h2>{current?.name??'Choose a workspace'}</h2><p className="workspace-path" title={current?.path}>{current?.path??'Your workspaces live here.'}</p>
      <div className="workspace-select"><input aria-label="Filter workspaces" placeholder="Filter workspaces" value={workspaceQuery} onChange={e=>setWorkspaceQuery(e.target.value)}/><select aria-label="Workspace" value={workspace} onChange={e=>void switchWorkspace(e.target.value)}><option value="">Select workspace</option>{(['pinned','recent','all'] as const).map(kind=><optgroup label={kind[0].toUpperCase()+kind.slice(1)} key={kind}>{groups[kind].map(w=><option key={w.id} value={w.id} disabled={w.valid===false}>{w.pinned?'★ ':''}{w.name}{w.valid===false?' — path missing':''}</option>)}</optgroup>)}</select></div>
      {current&&!compactScreen&&<button className="workspace-explorer" title="Opens this workspace on the host Windows desktop, not this device" disabled={current.valid===false||explorerBusy} onClick={()=>void openExplorer()}>Open on host PC</button>}
      {current&&explorerNotice?.id===current.id&&<small className="workspace-explorer-notice" role={explorerNotice.error?'alert':'status'}>{explorerNotice.text}</small>}
      <div className="workspace-add"><button className="manage-toggle add-toggle" aria-expanded={addWorkspaceOpen} aria-controls="workspace-add-form" onClick={e=>toggleWorkspaceAdd(e.currentTarget)}><span className="desktop-label">Add workspace</span><span className="mobile-label">Add a workspace</span> <span aria-hidden="true">⌄</span></button>
      {addWorkspaceOpen&&<div id="workspace-add-form" className="workspace-actions"><span className="workspace-form-heading" role="heading" aria-level={3} ref={workspaceCreateRef} tabIndex={-1}><span className="eyebrow">NEW WORKSPACE</span><strong>Add a workspace</strong><small>Choose a folder on this server, or enter its path.</small></span><label>New workspace path<input aria-label="Workspace path" placeholder="C:\\Dev\\my-app" value={path} onChange={e=>setPath(e.target.value)}/></label><div className="workspace-action-row"><button ref={browseTrigger} className="button-subtle" onClick={()=>setBrowseOpen(true)}>Browse folders</button><button className="button-primary" disabled={workspaceBusy==='add'||!path.trim()} onClick={()=>void addWorkspace()}>Add & open</button></div><button className="workspace-add-cancel" disabled={workspaceBusy==='add'} onClick={cancelWorkspaceAdd}>Cancel adding workspace</button></div>}</div>
      {current&&(compactScreen?workspaceMenu:<button className="manage-toggle" aria-expanded={workspaceTools} onClick={()=>setWorkspaceTools(v=>!v)}>{workspaceTools?'Hide workspace tools':'Manage workspace'} <span aria-hidden="true">⌄</span></button>)}
      {current&&workspaceTools&&<div className="workspace-management"><strong className="workspace-management-title">Edit selected workspace · {current.name}</strong>{compactScreen&&<button className="workspace-tools-close" onClick={()=>{setWorkspaceTools(false);requestAnimationFrame(()=>document.querySelector<HTMLElement>('.workspace-bar .workspace-menu summary')?.focus())}}>Hide workspace tools</button>}<label className="workspace-rename-label">Workspace name<input aria-label="Rename workspace" value={workspaceName} onChange={e=>{renameDirty.current=true;setWorkspaceName(e.target.value)}}/></label><button disabled={!!workspaceBusy||!workspaceName.trim()||workspaceName.trim()===current.name} onClick={()=>void renameWorkspace(workspaceName.trim())}>Rename</button><button disabled={!!workspaceBusy} onClick={()=>void togglePin()}>{current.pinned?'Unpin':'Pin'}</button><button className="workspace-remove" disabled={!!workspaceBusy} onClick={()=>void removeWorkspace(current)}>Remove from Console</button><small>Removing only detaches this registration — the folder and its Pi sessions stay on disk.</small><small>Last opened {new Date(current.lastOpenedAt).toLocaleString()}</small></div>}
      </section><section className="session-panel"><button className="back-link" onClick={()=>navigate('workspaces',workspace,'')}>{preferences.language==='ja'?'← ワークスペース':'← Workspaces'}</button><div className="session-context"><span className="eyebrow">IN WORKSPACE</span><strong>{current?.name??'Choose a workspace'}</strong>{workspaceMenu}{current&&explorerNotice?.id===current.id&&<small className="workspace-explorer-notice" role={explorerNotice.error?'alert':'status'}>{explorerNotice.text}</small>}</div><div className="section-heading"><h2>Sessions</h2><button className="new-session" disabled={creatingSession||!workspace||current?.valid===false} onClick={()=>void newSession()} aria-label="New Session">＋ <span>New Session</span></button></div>{creatingSession&&<p className="session-starting" role="status" aria-label="Session startup">Starting Pi session… Extensions may take up to a minute to load.</p>}{(sessions.length>0||sessionQuery)&&<input ref={searchRef} aria-label="Search sessions" placeholder="Search sessions…" value={sessionQuery} onChange={e=>setSessionQuery(e.target.value)}/>}<div className="session-list" aria-label="Session list">{visibleSessions.length?visibleSessions.map(s=><div key={s.id} className={`session-row${compactScreen?' compact-session-row':''}`}><button className={s.id===session?'current':''} aria-current={s.id===session?'page':undefined} disabled={!!recyclingScopes[JSON.stringify([workspace,s.id])]} onClick={()=>chooseSession(s.id)}><span className="session-dot" data-running={!!s.running} data-needs-input={!!s.decisionCount} aria-hidden="true"/><span className="session-copy"><b>{s.name??'New conversation'}</b><span>{s.decisionCount?`${s.decisionCount} need input · `:''}{s.running?'Running · ':''}{s.updatedAt?new Date(s.updatedAt).toLocaleString():'Just created'}</span></span></button>{compactScreen?<SessionItemMenu key={`${workspace}:${mobileView}:${s.id}`} name={s.name??'New conversation'} disabled={recycleDisabled(s)} onRecycle={()=>void recycleSession(s)}/>:<button className="session-recycle" aria-label={`Move ${s.name??'New conversation'} to Recycle Bin`} title="Move to Windows Recycle Bin" disabled={recycleDisabled(s)} onClick={()=>void recycleSession(s)}>🗑</button>}{compactScreen&&recycleErrors[JSON.stringify([workspace,s.id])]&&<small className="session-recycle-error" role="alert">Could not move this session: {recycleErrors[JSON.stringify([workspace,s.id])]}</small>}</div>):!creatingSession&&<p className="session-empty">{workspace?(sessionQuery?'No matching sessions.':'No sessions yet. Select New Session to start.'):'Select a workspace first.'}</p>}</div>
      <div className="runtime-line">Pi process <strong aria-label="runtime state">{creatingSession?'starting':snapshot?.runtime??'stopped'}</strong></div></section></aside>
      <div className={`content-pane${!compactScreen&&!executionExpanded?' execution-collapsed':''}`}>{chatSection}<div className="execution-area" id="execution-details">{kitStatus.available&&!kitBlocked&&!retryAvailable&&!kitStatus.job?.reportError&&<details className="kit-launch"><summary>New orchestrator run</summary><div className="kit-launch-body"><label>Orchestrator request<textarea aria-label="Orchestrator request" value={kitRequest} onChange={e=>setKitRequest(e.target.value)} placeholder="Describe the work for ludi-agent-kit…" disabled={!session||!!snapshot?.activeRunId||!!kitStatus.job?.running||sending||recycling}/></label><p className="kit-cost-note">Additional model calls: a new session first gets a Pi acknowledgement, the kit uses its configured models, and Pi saves a final answer. Provider charges may apply.</p><button disabled={!session||!kitRequest.trim()||!!snapshot?.activeRunId||!!kitStatus.job?.running||sending||recycling} onClick={()=>void startKit()}>Start orchestrator run</button><small>Starting this run pauses Pi chat. Stop does not cancel a kit run.</small></div></details>}{kitDecisions?.scope===decisionScope.current&&!!(kitDecisions.data.decisions.length||kitDecisions.data.canResume)&&<KitDecisionPanel key={`${decisionScope.current}:${kitDecisions.data.runId}`} data={kitDecisions.data} onAnswer={answerKit} onResume={retryKit} chatAllowed={chatAllowed} onContinueChat={retryAvailable&&!kitStatus.job?.needsInput?()=>setPausedChatAllowed(`${decisionScope.current}:${kitDecisions.data.runId}`):undefined}/>}{kitStatus.job&&<KitRunCard key={`${session}:${kitStatus.job.runId??kitStatus.job.startedAt}`} job={kitStatus.job} nodes={snapshot?.execution.nodes??[]} onRetryReport={retryKitReport} onMarkHandled={markKitReportHandled}/>}{!!activity.find(item=>item.sessionId===session)?.work.filter(w=>['running','waiting','blocked'].includes(w.status)).length&&<div className="live-work" role="status" aria-label="Current subagents and tasks">{activity.find(item=>item.sessionId===session)?.work.filter(w=>['running','waiting','blocked'].includes(w.status)).slice(0,4).map(w=><span key={w.id}>{w.kind}: {w.label} · {w.status}{w.action?` · ${w.action}`:''}</span>)}</div>}<ExecutionPanel key={`${workspace}:${session}`} state={snapshot?.execution} events={executionEvents} focusIssue={focusedIssue?.workspaceId===workspace&&focusedIssue.sessionId===session?focusedIssue:undefined} onInspect={nodeId=>post('/api/subagents/inspect',{workspaceId:workspace,sessionId:session,nodeId})} focusRootId={kitStatus.job?.runId ? `orchestrator:${kitStatus.job.runId}` : undefined}/></div></div></div>}
    {(mobileView==='chat'||mobileView==='execution')&&<nav className="mobile-nav" aria-label="Session views"><button onClick={()=>navigate('chat')} aria-current={mobileView==='chat'?'page':undefined}>Chat</button><button onClick={()=>navigate('execution')} aria-current={mobileView==='execution'?'page':undefined}>Execution · {executionRunning}{snapshot?.execution.failedCount?` !${snapshot.execution.failedCount}`:''}{snapshot?.execution.decisionCount?` ?${snapshot.execution.decisionCount}`:''}</button></nav>}
  </main>{filePreview&&<dialog ref={fileDialogRef} aria-label="Workspace file preview" className="file-preview" onCancel={e=>{e.preventDefault();fileRequest.current++;setFilePreview(undefined)}} onMouseDown={e=>{if(e.target!==e.currentTarget)return;const box=e.currentTarget.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom){fileRequest.current++;setFilePreview(undefined)}}}><header>{fileHistory.length>0&&<button aria-label="Back to previous file" onClick={backFile}>← Back</button>}<div><small>WORKSPACE FILE · {filePreview.format==='markdown'?'Markdown':filePreview.format==='code'?'Code':filePreview.format==='image'?'Image':filePreview.format==='video'?'Video':'Text'}</small><h2>{filePreview.path}</h2></div><div className="file-preview-actions"><button aria-label="Copy file contents" disabled={filePreview.content===undefined} onClick={()=>void copyFile()}>Copy</button><button ref={fileCloseRef} aria-label="Close file preview" onClick={()=>{fileRequest.current++;setFilePreview(undefined)}}>Close</button></div></header>{fileCopyStatus&&<span className="file-copy-status" role="status">{fileCopyStatus}</span>}<div className="file-preview-body">{filePreview.error?<p role="alert">{filePreview.error}</p>:filePreview.mediaUrl&&filePreview.format==='image'?<img className="file-preview-media" src={filePreview.mediaUrl} alt={filePreview.path}/>:filePreview.mediaUrl&&filePreview.format==='video'?<video className="file-preview-media" aria-label={`Video preview: ${filePreview.path}`} src={filePreview.mediaUrl} controls tabIndex={0} preload="metadata" playsInline/>:filePreview.content===undefined?<p role="status">Opening file…</p>:filePreview.format==='markdown'?<MarkdownContent text={filePreview.content} onOpenFile={(path,line)=>void openFile(path,line,true)}/>:filePreview.format==='code'?<div className="source-lines">{filePreview.content.split(/\r\n|\n|\r/).map((text,index)=><div key={index} className={filePreview.line===index+1?'source-line source-line-target':'source-line'} data-line={index+1}><span className="source-line-number" aria-hidden="true">{index+1}</span><span className="source-line-text">{text||' '}</span></div>)}</div>:<pre>{filePreview.content}</pre>}</div></dialog>}{preferences.petEnabled&&<PetWidget preferences={preferences} snapshot={snapshot} view={mobileView}/>}{browseOpen&&<DirectoryPicker initialPath={path.trim()||current?.path||''} onSelect={folder=>{setPath(folder);setBrowseOpen(false);requestAnimationFrame(()=>browseTrigger.current?.focus())}} onClose={()=>{setBrowseOpen(false);requestAnimationFrame(()=>browseTrigger.current?.focus())}}/>}</>;
}
if('serviceWorker' in navigator)window.addEventListener('load',()=>{void navigator.serviceWorker.register('/sw.js').catch(()=>{})});
createRoot(document.getElementById('root')!).render(<App/>);
