import React, { useEffect, useState } from 'react';
import type { SessionOptions } from '../shared/types.ts';

type Scope = 'planning'|'code'|'review'|'vision'|'browser';
type UserModel = {id:string;backend:string;name:string;provider:string;model:string;thinking?:string;vision:boolean;scopes:Scope[];capabilityClass?:string;costClass?:string};
const scopeLabels:{id:Scope;en:string;jp:string}[]=[{id:'planning',en:'Planning / investigation',jp:'計画・調査'},{id:'code',en:'Coding / testing',jp:'コード作業・テスト'},{id:'review',en:'Review',jp:'レビュー'},{id:'vision',en:'Image inspection',jp:'画像確認'},{id:'browser',en:'Browser automation',jp:'ブラウザー操作'}];
type Capability = { scope?:Scope; description:string; custom?:boolean; primary:string; fallback:string[]; status:string; candidates:string[]; placeholder:string[]; unbound:string[] };
type Backend = { description:string; vision:boolean; provider:string; model:string; thinking:string; status:string };
type Config = { userModels?:UserModel[]; maxUserModels?:number; overlayPath?:string; modelSource:string; modelSavePath:string; routingSavePath?:string; revision?:string; capabilities:Record<string,Capability>; disabledCapabilities?:{name:string;description:string}[]; backends:Record<string,Backend> };
type AvailableModel = SessionOptions['models'][number];
type RouteDraft = { name:string; description:string; primary:string; fallback:string[]; scope?:Scope };

function ModelPicker({models,value,onSelect,ariaLabel,disabled}:{models:AvailableModel[];value:{provider:string;model:string};onSelect:(model:AvailableModel)=>void;ariaLabel:string;disabled:boolean}){
  const [query,setQuery]=useState(''),[provider,setProvider]=useState('*');
  const selected=models.find(m=>m.provider===value.provider&&m.id===value.model);
  const providers=[...new Set(models.map(m=>m.provider))];
  const matching=models.filter(m=>(provider==='*'||m.provider===provider)&&`${m.provider} ${m.name} ${m.id}`.toLowerCase().includes(query.trim().toLowerCase()));
  const shown=matching.slice(0,80);if(selected&&!shown.includes(selected))shown.unshift(selected);
  return <div className="orchestrator-model-picker"><label>Available Pi model<select aria-label={ariaLabel} value={selected?JSON.stringify([selected.provider,selected.id]):''} disabled={disabled} onChange={event=>{const choice=models.find(m=>JSON.stringify([m.provider,m.id])===event.target.value);if(choice)onSelect(choice)}}><option value="">Choose a model…</option>{shown.map(m=><option key={JSON.stringify([m.provider,m.id])} value={JSON.stringify([m.provider,m.id])}>{m.provider} / {m.name}{m.name!==m.id?` (${m.id})`:''}</option>)}</select></label><div className="orchestrator-model-filters"><input aria-label={`${ariaLabel} search`} placeholder="Search name or ID" value={query} onChange={e=>setQuery(e.target.value)} disabled={disabled}/><select aria-label={`${ariaLabel} provider`} value={provider} onChange={e=>setProvider(e.target.value)} disabled={disabled}><option value="*">All providers</option>{providers.map(name=><option key={name} value={name}>{name}</option>)}</select></div><small>{matching.length>80?`First 80 of ${matching.length} models · refine search`:`${matching.length} matching models`}</small></div>;
}

export default function OrchestratorSettings({ja,availableModels}:{ja:boolean;availableModels?:SessionOptions['models']}){
  const label=(en:string,jp:string)=>ja?jp:en;
  const [config,setConfig]=useState<Config>();
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [userEdit,setUserEdit]=useState<string>();
  const [userDraft,setUserDraft]=useState({name:'',provider:'',model:'',thinking:'',vision:false,scopes:[] as Scope[],capabilityClass:'standard',costClass:'high'});
  const [modelEdit,setModelEdit]=useState<string>();
  const [modelSlot,setModelSlot]=useState('');
  const [modelValue,setModelValue]=useState({provider:'',model:''});
  const [routeEdit,setRouteEdit]=useState<string>();
  const [route,setRoute]=useState<RouteDraft>({name:'',description:'',primary:'',fallback:[]});
  const [quickChoices,setQuickChoices]=useState<Record<string,string>>({});
  const [newFallback,setNewFallback]=useState('');
  const load=async()=>{setError('');try{const response=await fetch('/api/orchestrator/settings');const data=await response.json();if(!response.ok)throw Error(data.error??`HTTP ${response.status}`);setConfig(data);setQuickChoices(Object.fromEntries(Object.entries(data.capabilities as Record<string,Capability>).map(([name,cap])=>[name,cap.candidates[0]??''])))}catch(e){setError((e as Error).message)}};
  useEffect(()=>{void load()},[]);
  const save=async(payload:Record<string,unknown>)=>{
    if(!config)return false;
    setBusy(true);setError('');setNotice('');
    try{
      const response=await fetch('/api/orchestrator/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...payload,revision:config.revision})});
      const data=await response.json();if(!response.ok)throw Error(data.error??`HTTP ${response.status}`);
      setConfig(data);setQuickChoices(Object.fromEntries(Object.entries(data.capabilities as Record<string,Capability>).map(([name,cap])=>[name,cap.candidates[0]??''])));
      setNotice(label('Saved. New and resumed runs use these settings.','保存しました。次の開始・再開時に適用されます。'));return true;
    }catch(e){setError((e as Error).message);return false}finally{setBusy(false)}
  };
  const userModels=config?.userModels??[];
  const userBackends=new Set(userModels.map(m=>m.backend));
  const beginUser=(model?:UserModel)=>{setError('');setNotice('');setUserEdit(model?.id??'new');setUserDraft({name:model?.name??'',provider:model?.provider??'',model:model?.model??'',thinking:model?.thinking??'',vision:model?.vision??false,scopes:model?.scopes??[],capabilityClass:model?.capabilityClass??'standard',costClass:model?.costClass??'high'})};
  const backendNames=config?Object.keys(config.backends):[];
  const bound=config?Object.entries(config.backends).filter(([,backend])=>backend.status==='bound'):[];
  const free=config?Object.entries(config.backends).filter(([name,backend])=>!userBackends.has(name)&&backend.status!=='bound'):[];
  const legacyBound=bound.filter(([name])=>!userBackends.has(name));
  const backendLabel=(name:string)=>{const user=userModels.find(m=>m.backend===name);if(user)return `${user.name} · ${user.provider} / ${user.model}`;const b=config?.backends[name];return b?.status==='bound'?`${b.provider} / ${b.model} (${name})`:`${name} · ${b?.status??'unavailable'}`};
  const beginModel=(name:string)=>{setNotice('');setError('');setModelEdit(name);setModelSlot(name==='new'?free[0]?.[0]??'':name);const b=name==='new'?undefined:config?.backends[name];setModelValue({provider:b?.status==='bound'?b.provider:'',model:b?.status==='bound'?b.model:''})};
  const beginRoute=(name:string)=>{setNotice('');setError('');setRouteEdit(name);const c=config?.capabilities[name];setRoute({name:name==='new'?'':name,description:c?.description??'',primary:c?.primary??bound[0]?.[0]??backendNames[0]??'',fallback:c?.fallback??[],scope:c?.scope??'code'});setNewFallback('')};
  const removeModel=async(name:string)=>{const used=Object.entries(config?.capabilities??{}).filter(([,cap])=>[cap.primary,...cap.fallback].includes(name)).map(([cap])=>cap);if(!window.confirm(label(`Remove ${backendLabel(name)} from this backend slot? ${used.length?`Capabilities using it: ${used.join(', ')}. `:''}They may fall back to other models or become unavailable.`,`この枠のモデル ${backendLabel(name)} を解除しますか？${used.length?`使用中の capability: ${used.join(', ')}。`:''}他のモデルに切り替わるか、使用できなくなる場合があります。`)))return;await save({kind:'backend',action:'delete',name,confirmed:true})};
  const removeRoute=async(name:string,cap:Capability)=>{if(!window.confirm(cap.custom?label(`Delete custom capability ${name}? This cannot be undone.`,`追加した capability ${name} を削除しますか？元に戻せません。`):label(`Disable built-in capability ${name}? Agents that require it may become unavailable. You can restore it later.`,`標準 capability ${name} を無効にしますか？必要とする agent が使用できなくなる場合があります。後で復元できます。`)))return;await save({kind:'capability',action:'delete',name,confirmed:true})};
  const availableFallback=backendNames.filter(name=>name!==route.primary&&!route.fallback.includes(name));
  const moveFallback=(index:number,direction:number)=>setRoute(old=>{const fallback=[...old.fallback],target=index+direction;[fallback[index],fallback[target]]=[fallback[target],fallback[index]];return {...old,fallback}});
  return <><h3>{label('Orchestrator models and capabilities','オーケストレータのモデルと capability')}</h3>
    <p>{label('Manage kit models separately from the Pi chat model. Changes apply at the next start or resume, not during a running task.','Kit 用モデルを Pi の会話モデルとは別に管理します。変更は次の開始・再開時に適用し、実行中のタスクには反映しません。')}</p>
    {error&&<div role="alert">{error} <button onClick={()=>void load()}>{label('Reload settings','設定を再読み込み')}</button></div>}{notice&&<p role="status">{notice}</p>}
    {!config&&!error&&<p>{label('Loading…','読み込み中…')}</p>}
    {config&&<>
      <section className="orchestrator-manager" aria-label="Registered orchestrator models"><div className="orchestrator-manager-heading"><h4>{label('Models','モデル')} ({userModels.length}/{config.maxUserModels??16})</h4><button disabled={busy||userModels.length>=(config.maxUserModels??16)} onClick={()=>beginUser()}>{label('Add model','モデルを追加')}</button></div>
        <p>{label('Register freely named models, then select them in capability routes below. Usage permissions restrict model routing, not tools or OS access. Existing kit assignments remain separate.','名称自由でモデルを登録し、下の capability 経路で選択します。使用許可はモデルの利用先を制限するもので、ツールや OS の権限ではありません。既存の Kit 割り当ては別に維持します。')}</p>
        {userModels.map(m=><div className="orchestrator-item" key={m.id}><div><strong>{m.name}</strong><small>{m.provider} / {m.model}</small><small>{m.scopes.length?m.scopes.map(s=>{const item=scopeLabels.find(i=>i.id===s)!;return label(item.en,item.jp)}).join(' · '):label('No usage permitted','使用許可なし')}</small></div><div className="orchestrator-item-actions"><button disabled={busy} aria-label={`Edit registered model ${m.name}`} onClick={()=>beginUser(m)}>{label('Edit','編集')}</button><button disabled={busy} aria-label={`Delete registered model ${m.name}`} onClick={()=>{if(window.confirm(label(`Delete ${m.name}? It will be removed from routes; remaining or default kit models may be used.`,`「${m.name}」を削除しますか？経路からも除外し、残りのモデルまたは Kit の標準経路を使用します。`)))void save({kind:'usermodel',action:'delete',id:m.id,confirmed:true}).then(ok=>{if(ok&&userEdit===m.id)setUserEdit(undefined)})}}>{label('Delete','削除')}</button></div></div>)}
        {!userModels.length&&<p>{label('No registered models. Add up to 16 models with any display name.','登録モデルはありません。自由な表示名で最大16件登録できます。')}</p>}
        {userEdit&&<div className="orchestrator-editor" aria-label="Registered model form"><label>{label('Display name','表示名')}<input aria-label="Model display name" maxLength={80} disabled={busy} value={userDraft.name} onChange={e=>setUserDraft(old=>({...old,name:e.target.value}))}/></label>
          {!!availableModels?.length&&<ModelPicker models={availableModels} value={userDraft} ariaLabel="Registered available Pi model" disabled={busy} onSelect={m=>setUserDraft(old=>({...old,provider:m.provider,model:m.id}))}/>}
          <label>Provider<input aria-label="Registered model provider" disabled={busy} value={userDraft.provider} onChange={e=>setUserDraft(old=>({...old,provider:e.target.value}))}/></label><label>Model ID<input aria-label="Registered model ID" disabled={busy} value={userDraft.model} onChange={e=>setUserDraft(old=>({...old,model:e.target.value}))}/></label>
          <label>Thinking<select aria-label="Registered model thinking" disabled={busy} value={userDraft.thinking} onChange={e=>setUserDraft(old=>({...old,thinking:e.target.value}))}><option value="">{label('Model default','モデルの標準設定')}</option>{['off','minimal','low','medium','high','xhigh','max'].map(v=><option key={v} value={v}>{v}</option>)}</select></label>
          <label>{label('Routing capability class','経路選択用の能力分類')}<select aria-label="Registered model capability class" disabled={busy} value={userDraft.capabilityClass} onChange={e=>setUserDraft(old=>({...old,capabilityClass:e.target.value}))}>{['basic','standard','strong','expert'].map(v=><option key={v} value={v}>{v}</option>)}</select></label>
          <label>{label('Cost class (unknown: high)','費用分類（不明なら high）')}<select aria-label="Registered model cost class" disabled={busy} value={userDraft.costClass} onChange={e=>setUserDraft(old=>({...old,costClass:e.target.value}))}>{['free','included','low','paid','high'].map(v=><option key={v} value={v}>{v}</option>)}</select></label><small>{label('Cost class is your declaration for kit routing, not a price check. Mark free / included only when verified.','費用分類は Kit の経路判断用の申告で、料金確認ではありません。free / included は確認済みの場合のみ指定してください。')}</small>
          <label className="orchestrator-checkbox"><input type="checkbox" aria-label="Supports image input" checked={userDraft.vision} disabled={busy} onChange={e=>setUserDraft(old=>({...old,vision:e.target.checked}))}/>{label('Model supports image input (verify provider support)','モデルが画像入力に対応（プロバイダーの対応を確認してください）')}</label>
          <fieldset disabled={busy}><legend>{label('Permitted uses','使用許可')}</legend>{scopeLabels.map(item=><label className="orchestrator-checkbox" key={item.id}><input type="checkbox" aria-label={`Allow ${item.id}`} checked={userDraft.scopes.includes(item.id)} onChange={e=>{const checked=e.target.checked;setUserDraft(old=>({...old,scopes:checked?[...old.scopes,item.id]:old.scopes.filter(s=>s!==item.id)}))}}/>{label(item.en,item.jp)}</label>)}</fieldset>
          <small>{label('Image inspection requires both image-input support and permission. Both the route and agent role must be allowed (e.g. image review also needs Review). Registration does not test the provider connection.','画像確認には画像入力対応と使用許可の両方が必要です。経路と agent の役割を両方許可してください（画像レビューならレビューも必要）。登録だけでは接続確認になりません。')}</small>
          <div className="orchestrator-item-actions"><button disabled={busy||!userDraft.name.trim()||!userDraft.provider.trim()||!userDraft.model.trim()} onClick={()=>void save({kind:'usermodel',action:userEdit==='new'?'create':'update',...(userEdit!=='new'?{id:userEdit}:{}),...userDraft}).then(ok=>{if(ok)setUserEdit(undefined)})}>{label('Save registered model','登録モデルを保存')}</button><button disabled={busy} onClick={()=>setUserEdit(undefined)}>{label('Cancel','キャンセル')}</button></div></div>}
      </section>
      <details><summary>{label('Legacy kit assignments','既存の Kit 割り当て')}</summary><section className="orchestrator-manager" aria-label="Orchestrator models"><div className="orchestrator-manager-heading"><h4>{label('Kit assignments','Kit の割り当て')}</h4><button disabled={busy||!free.length} onClick={()=>beginModel('new')}>{label('Assign legacy model','既存枠に割り当て')}</button></div>
        <p>{label('Legacy fixed assignments are preserved. Use the section above for freely named registrations and usage permissions.','既存の固定割り当ては保持しています。自由名の登録と使用許可は上の欄を使ってください。')}</p>
        {!free.length&&<small>{label('All kit slots are used. This kit version cannot create new backend slots; edit or remove an assignment to free one.','Kit の枠はすべて使用中です。この kit では新しい backend 枠は作れません。割り当てを編集・解除してください。')}</small>}
        {legacyBound.length?legacyBound.map(([name,b])=><div className="orchestrator-item" key={name}><div><strong>{b.provider} / {b.model}</strong><small>{name}{b.vision?' · vision':''}{b.description?` · ${b.description}`:''}</small></div><div className="orchestrator-item-actions"><button disabled={busy} onClick={()=>beginModel(name)} aria-label={`Edit model ${name}`}>{label('Edit','編集')}</button><button disabled={busy} onClick={()=>void removeModel(name)} aria-label={`Remove model ${name}`}>{label('Remove','解除')}</button></div></div>):<p>{label('No model is assigned yet. Add one to get started.','モデルが未設定です。「モデルを追加」から設定してください。')}</p>}
        {modelEdit&&<div className="orchestrator-editor" aria-label={modelEdit==='new'?'Add model form':`Edit model ${modelEdit}`}><h5>{modelEdit==='new'?label('Add model','モデルを追加'):label(`Edit model · ${modelEdit}`,`モデルを編集 · ${modelEdit}`)}</h5>
          {modelEdit==='new'&&<label>{label('Backend slot','Kit の割り当て先')}<select aria-label="Model backend slot" disabled={busy} value={modelSlot} onChange={e=>setModelSlot(e.target.value)}>{free.map(([name])=><option key={name} value={name}>{name}{config.backends[name].description?` · ${config.backends[name].description}`:''}</option>)}</select></label>}
          {!!availableModels?.length&&<ModelPicker models={availableModels} value={modelValue} onSelect={m=>setModelValue({provider:m.provider,model:m.id})} ariaLabel="Kit available Pi model" disabled={busy}/>}
          {!availableModels?.length&&<small>{label('Open a Pi session to browse models, or enter a provider and model ID manually.','モデル一覧を使うには Pi セッションを開いてください。provider とモデル ID の手入力もできます。')}</small>}
          <label>Provider<input aria-label="Kit model provider" value={modelValue.provider} disabled={busy} onChange={e=>setModelValue(old=>({...old,provider:e.target.value}))}/></label><label>Model ID<input aria-label="Kit model ID" value={modelValue.model} disabled={busy} onChange={e=>setModelValue(old=>({...old,model:e.target.value}))}/></label>
          <div className="orchestrator-item-actions"><button disabled={busy||!modelSlot||!modelValue.provider.trim()||!modelValue.model.trim()} onClick={()=>void save({kind:'backend',name:modelSlot,...modelValue}).then(ok=>{if(ok)setModelEdit(undefined)})}>{label('Save model','モデルを保存')}</button><button disabled={busy} onClick={()=>setModelEdit(undefined)}>{label('Cancel','キャンセル')}</button></div></div>}
      </section></details>
      <section className="orchestrator-manager" aria-label="Orchestrator capabilities"><div className="orchestrator-manager-heading"><h4>Capabilities</h4><button disabled={busy||!backendNames.length} onClick={()=>beginRoute('new')}>{label('Add capability','capability を追加')}</button></div><p>{label('A capability tries its first model, then each fallback in order. Creating one does not automatically assign it to an agent.','capability は優先モデルから順に代替モデルを試します。追加しただけでは agent に割り当てられません。')}</p>
        {Object.entries(config.capabilities).map(([name,cap])=><div className="orchestrator-item" key={name}><div><strong>{name}</strong><small>{cap.description||label('No description','説明なし')}</small><small>{[cap.primary,...cap.fallback].map(backendLabel).join(' → ')}</small><small>{label('Permitted candidates','使用可能な候補')}: {cap.candidates.length?cap.candidates.map(backendLabel).join(' → '):label('None','なし')}</small><small>{cap.status==='bound'?label('Ready','設定済み'):cap.status==='placeholder'?label('Needs a model','モデルが必要'):label('Unavailable','利用不可')}{cap.custom?' · custom':''}</small></div><div className="orchestrator-item-actions"><button disabled={busy} onClick={()=>beginRoute(name)} aria-label={`Edit capability ${name}`}>{label('Edit route','経路を編集')}</button><button disabled={busy} onClick={()=>void removeRoute(name,cap)} aria-label={`${cap.custom?'Delete':'Disable'} capability ${name}`}>{cap.custom?label('Delete','削除'):label('Disable','無効化')}</button></div></div>)}
        {!!config.disabledCapabilities?.length&&<div className="orchestrator-disabled"><strong>{label('Disabled built-in capabilities','無効化した標準 capability')}</strong>{config.disabledCapabilities.map(item=><div key={item.name} className="orchestrator-item"><span>{item.name} · {item.description}</span><button disabled={busy} onClick={()=>void save({kind:'capability',action:'restore',name:item.name})} aria-label={`Restore capability ${item.name}`}>{label('Restore','復元')}</button></div>)}</div>}
        {routeEdit&&<div className="orchestrator-editor" aria-label={routeEdit==='new'?'Add capability form':`Edit capability ${routeEdit}`}><h5>{routeEdit==='new'?label('Add capability','capability を追加'):label(`Edit route · ${routeEdit}`,`経路を編集 · ${routeEdit}`)}</h5>
          {routeEdit==='new'&&<label>{label('Capability name (lowercase letters, digits, hyphens)','名前（小文字・数字・ハイフン）')}<input aria-label="New capability name" value={route.name} disabled={busy} maxLength={64} onChange={e=>setRoute(old=>({...old,name:e.target.value}))}/></label>}
          {(routeEdit==='new'||config.capabilities[routeEdit]?.custom)&&<label>{label('Usage permission group','使用許可の分類')}<select aria-label="Capability permission scope" disabled={busy} value={route.scope??'code'} onChange={e=>setRoute(old=>({...old,scope:e.target.value as Scope}))}>{scopeLabels.map(s=><option key={s.id} value={s.id}>{label(s.en,s.jp)}</option>)}</select></label>}
          <label>{label('What is it for?','用途・説明')}<input aria-label="Capability description" value={route.description} disabled={busy} maxLength={300} onChange={e=>setRoute(old=>({...old,description:e.target.value}))}/></label>
          <label>{label('First model','優先モデル')}<select aria-label="Capability primary model" value={route.primary} disabled={busy} onChange={e=>{const primary=e.target.value;setRoute(old=>({...old,primary,fallback:old.fallback.filter(name=>name!==primary)}))}}>{backendNames.map(name=><option key={name} value={name}>{backendLabel(name)}</option>)}</select></label>
          <strong>{label('Fallback order','代替モデルの順序')}</strong>{route.fallback.map((name,index)=><div className="orchestrator-fallback" key={name}><span>{index+1}. {backendLabel(name)}</span><div className="orchestrator-item-actions"><button aria-label={`Move ${name} up`} disabled={busy||index===0} onClick={()=>moveFallback(index,-1)}>↑</button><button aria-label={`Move ${name} down`} disabled={busy||index===route.fallback.length-1} onClick={()=>moveFallback(index,1)}>↓</button><button aria-label={`Remove fallback ${name}`} disabled={busy} onClick={()=>setRoute(old=>({...old,fallback:old.fallback.filter(value=>value!==name)}))}>×</button></div></div>)}
          {availableFallback.length>0&&<label>{label('Add a fallback','代替モデルを追加')}<select aria-label="Add fallback model" value={newFallback} disabled={busy} onChange={e=>{const name=e.target.value;if(!name)return;setRoute(old=>({...old,fallback:[...old.fallback,name]}));setNewFallback('')}}><option value="">{label('Choose a model…','モデルを選択…')}</option>{availableFallback.map(name=><option key={name} value={name}>{backendLabel(name)}</option>)}</select></label>}
          <div className="orchestrator-item-actions"><button disabled={busy||!route.primary||routeEdit==='new'&&!/^[a-z][a-z0-9-]*$/.test(route.name)} onClick={()=>void save({kind:'capability',...(routeEdit==='new'?{action:'create'}:{}),...route}).then(ok=>{if(ok)setRouteEdit(undefined)})}>{label('Save capability','capability を保存')}</button><button disabled={busy} onClick={()=>setRouteEdit(undefined)}>{label('Cancel','キャンセル')}</button></div></div>}
      </section>
      <section className="orchestrator-manager" aria-label="Quick model choices"><h4>{label('Quick model choices','よく使う作業の優先モデル')}</h4>{[{name:'strong-code',en:'Coding tasks',jp:'コード作業'},{name:'orchestration',en:'Model-based planning',jp:'モデルによる計画'}].filter(item=>config.capabilities[item.name]).map(item=>{const cap=config.capabilities[item.name],selected=quickChoices[item.name]??'';const fallback=[cap.primary,...cap.fallback].filter((name,index,all)=>name!==selected&&all.indexOf(name)===index);return <div className="orchestrator-quick-route" key={item.name}><label>{label(item.en,item.jp)}<select aria-label={`${item.name} preferred model`} value={selected} disabled={busy||!bound.length} onChange={e=>setQuickChoices(old=>({...old,[item.name]:e.target.value}))}><option value="">{label('Choose a configured model','設定済みモデルを選択')}</option>{bound.map(([name])=><option key={name} value={name}>{backendLabel(name)}</option>)}</select></label><small>{label('Order after saving','保存後の順序')}: {selected?[selected,...fallback].join(' → '):'—'}</small><button disabled={busy||!selected||selected===cap.primary} onClick={()=>void save({kind:'capability',name:item.name,primary:selected,fallback})}>{label('Use this model','このモデルを優先')}</button>{item.name==='orchestration'&&<small>{label('Only used with the model planner; the default rules planner does not call a planning model.','モデルプランナーを選択した場合だけ使用します。標準のルールプランナーは計画用モデルを呼びません。')}</small>}</div>})}</section>
      <details className="orchestrator-advanced"><summary>{label('Storage and kit limits','保存先と kit の制約')}</summary><p>{label('Named registrations and their routes are stored by Console and apply to runs started or resumed through Console, not the kit CLI. Legacy assignments and routes keep their original storage. Credentials are never changed here.','自由名の登録とその経路は Console の保存先に保存し、Console から開始・再開したランに適用します。Kit の CLI には適用しません。既存の固定割り当て・経路は従来の保存先を維持します。認証情報は変更しません。')}</p><p className="orchestrator-path">{label('Registered model storage','登録モデルの保存先')}: <code>{config.overlayPath??'—'}</code><br/>{label('Effective model source','有効なモデル設定元')}: <code>{config.modelSource}</code><br/>{label('Model save path','モデルの保存先')}: <code>{config.modelSavePath}</code><br/>{label('Capability save path','capability の保存先')}: <code>{config.routingSavePath??'—'}</code></p></details>
    </>}
  </>;
}
