import React, { useEffect, useState } from 'react';
import type { ConsolePreferences } from './preferences.ts';
import OrchestratorSettings from './OrchestratorSettings.tsx';
import type { SessionOptions } from '../shared/types.ts';
type Section='sessions'|'orchestrator'|'cleanup'|'startup'|'overview'|'language'|'appearance'|'pet';
const labels:{[key in Section]:[string,string]}={sessions:['Sessions','セッション'],orchestrator:['Orchestrator','オーケストレータ'],cleanup:['Automatic cleanup','自動整理'],startup:['Start with Windows','Windows 起動時'],overview:['About the app','アプリの概要'],language:['Language','言語'],appearance:['Appearance','見た目'],pet:['Pet','ペット']};
export default function SettingsPage({preferences,onChange,onBack,workspaceCount,sessionCount,connected,availableModels}:{preferences:ConsolePreferences;onChange:(value:ConsolePreferences)=>void;onBack:()=>void;workspaceCount:number;sessionCount:number;connected:boolean;availableModels?:SessionOptions['models']}){
  const [section,setSection]=useState<Section>('sessions');const [showSection,setShowSection]=useState(false);const ja=preferences.language==='ja';
  const [pets,setPets]=useState<{id:string;displayName:string;source:string}[]>([]);
  const [retention,setRetention]=useState<{enabled:boolean;days:number;lastRun?:{at:string;moved:number;errors:number}}>();
  const [daysText,setDaysText]=useState('30');const [retentionError,setRetentionError]=useState('');const [retentionBusy,setRetentionBusy]=useState(false);
  const [startup,setStartup]=useState<{supported:boolean;enabled:boolean;installed:boolean;conflict?:boolean}>();const [startupBusy,setStartupBusy]=useState(false);const [startupError,setStartupError]=useState('');
  useEffect(()=>{let mounted=true;fetch('/api/session-retention').then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(d=>{if(mounted){setRetention(d);setDaysText(String(d.days))}}).catch(e=>{if(mounted)setRetentionError((e as Error).message)});return()=>{mounted=false}},[]);
  const saveRetention=async(enabled:boolean)=>{const days=Number(daysText);if(!Number.isSafeInteger(days)||days<1||days>3650){setRetentionError(label('Enter 1–3650 whole days.','1～3650 の整数を入力してください。'));return}setRetentionBusy(true);try{const response=await fetch('/api/session-retention',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({enabled,days})});const value=await response.json();if(!response.ok)throw new Error(value.error??`HTTP ${response.status}`);setRetention(value);setRetentionError('')}catch(e){setRetentionError((e as Error).message)}finally{setRetentionBusy(false)}};
  useEffect(()=>{let mounted=true;fetch('/api/startup').then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(d=>{if(mounted)setStartup(d)}).catch(e=>{if(mounted)setStartupError((e as Error).message)});return()=>{mounted=false}},[]);
  const changeStartup=async(enabled:boolean)=>{setStartupBusy(true);try{const response=await fetch('/api/startup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({enabled})});const value=await response.json();if(!response.ok)throw new Error(value.error??`HTTP ${response.status}`);setStartup(value);setStartupError('')}catch(e){setStartupError((e as Error).message)}finally{setStartupBusy(false)}};
  useEffect(()=>{let mounted=true;fetch('/api/pets').then(r=>r.ok?r.json():{pets:[]}).then(d=>{if(mounted)setPets(Array.isArray(d.pets)?d.pets:[])}).catch(()=>{});return()=>{mounted=false}},[]);
  const label=(en:string,jp:string)=>ja?jp:en;
  const change=(part:Partial<ConsolePreferences>)=>onChange({...preferences,...part});
  return <section className={`settings-page ${showSection?'settings-detail':''}`} aria-label="Settings">
    <div className="settings-heading"><button className="settings-back" onClick={()=>{if(showSection)setShowSection(false);else onBack()}}>{showSection?label('← Settings','← 設定'):label('← Back','← 戻る')}</button><h2>{showSection?labels[section][ja?1:0]:label('Settings','設定')}</h2></div>
    <div className="settings-body"><nav className="settings-menu" aria-label="Settings sections">{(Object.keys(labels) as Section[]).map(id=><button key={id} aria-current={section===id?'page':undefined} onClick={()=>{setSection(id);setShowSection(true)}}>{labels[id][ja?1:0]}<span aria-hidden="true">›</span></button>)}</nav>
      <div className="settings-content">
        {section==='sessions'&&<><h3>{label('Sessions','セッション')}</h3><p>{label('Choose which view opens when you select a session.','セッションを開いたときの表示を選びます。')}</p><label className="settings-row"><span>{label('Default session view','セッションの初期表示')}</span><select aria-label="Default session view" value={preferences.defaultSessionView} onChange={e=>change({defaultSessionView:e.target.value as 'chat'|'execution'})}><option value="chat">Chat</option><option value="execution">Execution</option></select></label></>}
        {section==='orchestrator'&&<OrchestratorSettings ja={ja} availableModels={availableModels}/>}
        {section==='cleanup'&&<><h3>{label('Automatic cleanup','自動整理')}</h3><div className="retention-settings"><h4>{label('Recycle old sessions','古いセッションをゴミ箱へ')}</h4><p>{label('All Pi session files belonging to registered workspaces, including sessions visible in other Pi apps, may be moved to this server’s Windows Recycle Bin. Open sessions here are skipped; Pi Console cannot detect every worker in other apps. Off by default.','登録済みワークスペースの Pi セッションファイル（他の Pi アプリから見えるものも含む）を、このサーバーの Windows ゴミ箱に移動します。ここで開いているセッションは除外しますが、他アプリの全ワーカーは検出できません。初期状態はオフです。')}</p><label className="settings-row"><span>{label('Automatically recycle','自動でゴミ箱へ移動')}</span><input aria-label="Automatically recycle sessions" type="checkbox" disabled={!retention||retentionBusy} checked={retention?.enabled??false} onChange={e=>void saveRetention(e.target.checked)}/></label><label className="settings-row"><span>{label('Days since last modification','最終更新からの日数')}</span><input aria-label="Retention days" type="number" min="1" max="3650" step="1" value={daysText} onChange={e=>setDaysText(e.target.value)}/></label><button disabled={!retention||retentionBusy} onClick={()=>void saveRetention(retention?.enabled??false)}>{label('Save retention days','日数を保存')}</button><small>{label('Checks on enable, at server start, then hourly. At most 50 files per check; file modification time decides age.','有効化時・サーバー起動時・以後1時間ごとに確認します。1回最大50件で、ファイルの最終更新日時を基準にします。')}</small>{retention?.lastRun&&<small>{label('Last check','前回の確認')}: {new Date(retention.lastRun.at).toLocaleString()} · {retention.lastRun.moved} {label('moved','移動')} · {retention.lastRun.errors} {label('errors','エラー')}</small>}{retentionError&&<p role="alert">{retentionError}</p>}</div></>}
        {section==='startup'&&<><h3>{label('Start with Windows','Windows 起動時に開始')}</h3><p>{label('Add Pi Console to this Windows user’s Startup folder. It starts after sign-in, not as a system service; an already occupied port is left untouched. Pi packages have no install hook, so a trusted interactive Pi session installs the shortcut on first load, or you can install it now.','このユーザーの Windows スタートアップフォルダに Pi Console を登録します。サインイン後に起動し、Windows サービスではありません。使用中のポートは変更しません。Pi パッケージにはインストール時フックがないため、信頼済みの対話 Pi を最初に起動したときに登録します。ここから今すぐ登録することもできます。')}</p><label className="settings-row"><span>{label('Start automatically at sign-in','サインイン時に自動起動')}</span><input aria-label="Start with Windows" type="checkbox" disabled={!startup?.supported||startupBusy} checked={startup?.enabled??false} onChange={e=>void changeStartup(e.target.checked)}/></label>{startup?.supported&&<div className="startup-status"><span>{startup.installed?label('Startup shortcut installed','スタートアップに登録済み'):startup.conflict?label('Another entry uses this shortcut name','同名の別の項目があります'):label('Startup shortcut not yet installed','まだ登録されていません')}</span>{startup.enabled&&!startup.installed&&!startup.conflict&&<button disabled={startupBusy} onClick={()=>void changeStartup(true)}>{label('Install now','今すぐ登録')}</button>}</div>}{startup&&!startup.supported&&<p>{label('Windows only.','Windows 専用です。')}</p>}{startupError&&<p role="alert">{startupError}</p>}</>}
        {section==='overview'&&<><h3>{label('About the app','アプリの概要')}</h3><p>{label('Pi Console is a local-first web console for Pi. Open a server-local workspace, chat with a separate Pi RPC session and inspect its execution timeline. The browser interface can be installed as a PWA, but Pi must remain running on the server.','Pi Console は Pi 用のローカル優先 Web コンソールです。サーバー上のワークスペースを開き、独立した Pi RPC セッションで会話し、実行タイムラインを確認できます。画面は PWA としてインストールできますが、Pi はサーバーで起動している必要があります。')}</p><p>{label('Display preferences are saved in this browser; workspace metadata and server settings stay on the server.','表示設定はこのブラウザに、ワークスペース情報とサーバー設定はサーバーに保存されます。')}</p><div className="settings-row"><span>{label('Connection','接続')}</span><strong>{connected?label('Server ready','サーバー接続中'):label('Offline','オフライン')}</strong></div><div className="settings-row"><span>{label('Workspaces','ワークスペース')}</span><strong>{workspaceCount}</strong></div><div className="settings-row"><span>{label('Sessions in selected workspace','選択中のワークスペースのセッション')}</span><strong>{sessionCount}</strong></div><p><a href="/third-party-notices" target="_blank" rel="noopener noreferrer">{label('Open-source licenses and notices','使用 OSS・ライセンス表記')}</a></p></>}
        {section==='language'&&<><h3>{label('Language','言語')}</h3><p>{label('Language for the settings page and navigation. Chat content and other controls remain in English.','設定ページとナビゲーションの言語です。チャット内容やその他の操作は英語のままです。')}</p><label className="settings-row"><span>{label('Display language','表示言語')}</span><select aria-label="Display language" value={preferences.language} onChange={e=>change({language:e.target.value as 'en'|'ja'})}><option value="en">English</option><option value="ja">日本語</option></select></label></>}
        {section==='appearance'&&<><h3>{label('Appearance','見た目')}</h3><p>{label('Choose a color palette for this browser.','このブラウザの配色を選びます。')}</p><label className="settings-row"><span>{label('Color palette','配色')}</span><select aria-label="Color palette" value={preferences.appearance} onChange={e=>change({appearance:e.target.value as 'violet'|'graphite'})}><option value="violet">Violet</option><option value="graphite">Graphite</option></select></label></>}
        {section==='pet'&&<><h3>{label('Pet','ペット')}</h3><p>{label('Codex-compatible packages on this server. Auto prefers Fio. Drag the pet with a finger or mouse to move it; it stays on-screen and wanders nearby afterward.','サーバーにある Codex 互換ペットを読み込みます。自動ではフィオを優先します。指やマウスでつかんで移動でき、画面からはみ出しません。')}</p><label className="settings-row"><span>{label('Show companion','ペットを表示')}</span><input aria-label="Show companion" type="checkbox" checked={preferences.petEnabled} onChange={e=>change({petEnabled:e.target.checked})}/></label><label className="settings-row"><span>{label('Pet package','ペットの種類')}</span><select aria-label="Pet package" disabled={!preferences.petEnabled||pets.length===0} value={preferences.petId&&pets.some(p=>p.id===preferences.petId)?preferences.petId:''} onChange={e=>change({petId:e.target.value})}><option value="">{label('Auto (Fio if available)','自動（フィオを優先）')}</option>{pets.map(p=><option key={p.id} value={p.id}>{p.displayName} ({p.source})</option>)}</select></label>{pets.length===0&&<small>{label('No pet packages found on this server.','このサーバーにはペットが見つかりません。')}</small>}<label className="settings-row"><span>{label('Scale','サイズ')}</span><select aria-label="Pet scale" disabled={!preferences.petEnabled} value={preferences.petScale} onChange={e=>change({petScale:Number(e.target.value) as ConsolePreferences['petScale']})}>{[0.5,0.75,1,1.5,2].map(v=><option key={v} value={v}>{v}×</option>)}</select></label><label className="settings-row"><span>{label('Starting corner','初期位置')}</span><select aria-label="Pet position" disabled={!preferences.petEnabled} value={preferences.petPosition} onChange={e=>change({petPosition:e.target.value as 'left'|'right'})}><option value="right">{label('Bottom right','右下')}</option><option value="left">{label('Bottom left','左下')}</option></select></label></>}
        <small>{label('Display settings live in this browser; cleanup and startup are configured on the server.','表示設定はこのブラウザに保存します。自動整理とスタートアップはサーバー側で設定します。')}</small>
      </div></div>
  </section>
}
